### ISSUE TITLE
New "Goldilocks" synthetic datasets for automated tests

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#100]
Datasets where taxa are not too closely related (E.coli / Shigella) or too far apart (no close relatives in database). These will replace the older, hard datasets we're currently using for testing.

To measure things like linkage accuracy, etc.

**Comment by koadman** [comment]
grinder is a nice tool for making synthetic datasets:
http://sourceforge.net/projects/biogrinder/files/biogrinder/Grinder-0.4.5/

It uses a fasta file of genomes as input and can sample reads under various sampling strategies. Parameters of relevance to us could be:
`grinder -read_dist 105 -insert_dist 400 normal 50 -md poly4 3e-3 3.3e-8 -mr 95 5 -genome_file <your genome file> -total_reads XXXXX`

**Comment by hollybik** [comment]
Working on the Eukaryotes now, and sitting down with Jenna on Wednesday to go through the Bacterial and Archaeal tree and pick out a range of non-nucleated genomes for compiling this dataset. After we compile a list of target taxa, will move forward with grinder to subsample genomes.

**Comment by gjospin** [comment]
The Kangaroo was born today and is knocking out genomes!!!!

I am working on a new branch called 040512_sims that will add a new PS mode called sim.
There are still a few things to tweak but the idea is there.
So far it picks the top X taxa with highest PD from our concatenated tree and X random taxa from that tree and generated Y Illumina paired ends reads in a PS_temp/Sims directory.  

To do : Have a user specified output directory so multiple instances of simulations don't write on top of each other
To do : Generate other reads using more flexible parameter inputs
To do : Think of shorter file naming convention that are still easy to understand. Grinder adds its own junk at the end which can make the file names really long.

**Comment by gjospin** [comment]
Added a randomly generated abundance for all taxa selected.
Ready to merge to devel, waiting for appropriate time do the merging.
