### ISSUE TITLE
Add meaningful website content

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#103]
The current phylosift website is very sparse in content and it would be nice if it could give people some idea of what we're up to and how it might be interesting and useful to them.

**Comment by hollybik** [comment]
Posted a bunch of updates to the web tonight - Found us a logo for twitter, added a "People" page with links to our internet stuff, and am in the process of updating the "About" page with a proper description.

**Comment by hollybik** [comment]
We've established all our basic information and sites now, I think - the GitHub, Google Group, Blog, and Twitter. Have updated all these sites with the "standard" info PhyloSift and cross links to all these different sites.  

Next step is to talk about some of the recent coding updates on the blog. I'm also going to be compiling tutorials "How do I analyze X data in PhyloSift" - X = 16S, genome data, metagenome sequences. This will give users an idea of the wide variety of analyses that are possible, specific challenges with each one (Bacteria versus Euks), and the type of outputs which they can expect to see from the software.

**Comment by koadman** [comment]
looking much better now
