### ISSUE TITLE
Ability to handle raw 454 data files as input

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#112]
Biologists are still leaning towards 454 (and probably will be for the next few years), so we should probably be able to handle these raw file inputs in addition to Illumina data

**Comment by koadman** [comment]
this would be good but what is required? do we want to take .sff as input? or can we expect users to extract the reads into fasta or fastq? there is a free/open source utility to do that (extract_sff.py I think). trivial format issues aside, good support for 454 will come from solving Issue #60 (frameshift support).

**Comment by hollybik** [comment]
Format will be .fasta file and .qual files (the output of the .sff conversion tools - each line of sequence is comparable across files). No one really deals with flow grams (.sff files) unless you are denoisng; the sequencing facility usually converts them before they hand over the data.

**Comment by koadman** [comment]
denoting == denoising? is there any reason why the separate .fasta and .qual files couldn't be merged into a .fastq to be compatible with the existing workflow?

**Comment by hollybik** [comment]
Hmm, I guess in theory this is possible but in reality the fastQ and 454 outputs are very different. 
For 454 the .fasta files are nucleotide sequences and the .qual file is quality scores in 2-digit numerical format, e.g.

fasta - ATCGATCG
qual - 30 40 50 50 50 50 50 

The data is paired so lines in each file correspond to one another, but looking at the fastq illumina files the quality scores seem to be way different and gibberish-y with lots of alphanumeric characters (so not sure how you'd translate 454 quals to Illumina quality reads--unless these scripts already exist?)

**Comment by koadman** [comment]
http://lmgtfy.com/?q=sff+to+fastq
