### ISSUE TITLE
Clarify the filtering/processing steps conducted on raw data (non-assembled reads)

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#113]
If we're using raw data files (Illumina, P-E, or 454), what are the filtering and processing criteria for these reads?

**Comment by koadman** [comment]
This depends in large part on library prep, sequencing protocol, and base calling algorithm. Generally these steps include adapter trimming and quality filtering, but there seems to be so much variability in these steps that it may be difficult to standardize.

**Comment by hollybik** [comment]
Will incorporate this into the GoogleDoc discussions
