### ISSUE TITLE
Rapsearch Vs Last performance comparison

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#116]

**Comment by gjospin** [comment]
Tested using a full illumina lane (~40 million reads).
Duration 1.5 hours (2 hours at the most)
Last with -e300 gets 0 hits (too high a score considering the short length of reads)
Last with -e150 gets 89k hits
Last with -e100 gets  2.7 million hits

Rapsearch on the same data takes 20hours and gets 3.7 million hits.

It would be interesting to see how many hits we get after hmmalign/masking to see if the increased number of hits matter of if we are discarding them all anyways.

**Comment by koadman** [comment]
Sounds like lastal is highly competitive. This is great news for searching the extended marker db.
