### ISSUE TITLE
Output needed: jplace file converted to tree file with placed reads

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#124]
In addition to the jplace file, biologists will want to see where their reads were placed on the reference tree and what sequences went where. Names aren't so important for raw reads, but we'll have to assume that people will also be analyzing OTUs and contigs where they'll want to see the taxon labels on this tree (e.g. so they can look back in their data and do biology).

Right now it looks like PhyloSift only outputs the jplace file with the Edge PCoA viewable.

**Comment by koadman** [comment]
What exactly do you want to visualize? Phylosift does not generate OTUs. There can and will be thousands of reads scattered all over a tree, and the probability distribution over any individual read's placement may be diffuse so picking a single attachment point to visualize may not be very informative. guppy can do this conversion but I'm afraid it might be misleading. guppy provides a means to color/weight reference tree branches with probability masses. Could that be of use? These can only be viewed in archaeopteryx (part of forester.jar). Do we need to package that up with phylosift? With about 3000 taxa I'm afraid the reference tree will be too unwieldly for casual browsing. There will also be several different trees, one for each marker gene. Which one do we show people?

**Comment by hollybik** [comment]
So I think biologists would want to ask "what taxa in my samples are being placed on these branches" when they see the weighted/coloured branches from guppy. The visualization issues seem significant (tackling these can be a long-term goal), so maybe that's not the best route right now. I think we need to give users some more informative idea of what guppy is actually doing rather than just churning out a tree picture (although this is also important). Even at the risk of overloading them with information at this point - e.g. lots of files, one for each marker gene.

So for any given branch that is colored in the Edge PCoA visualization, on the tree you would generate a branch label that could be cross referenced with another text file containing the taxa (contigs, OTUs, read identifiers - whatever type of sequences you started with in PhyloSift) placed at that significant branch with the corresponding probability distributions. Maybe you could \* taxa that have high placement probabilities on a given branch (giving the user a way to have some sort of confidence values for how well the algorithms are working).

Can explain this further in person if this is unclear - might help to draw out my vision of outputs!!

**Comment by koadman** [comment]
well, i think it would also be helpful if you could have a look at what guppy + forester can already do for viz and decide whether one of those output types is sufficient or if you need something new. Look here for guppy docs: http://matsen.github.com/pplacer/guppy.html

gunna close this for now and can re-open when we have a specific goal determined.
