### ISSUE TITLE
VM/Cloud computing options for PhyloSift

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#125]
Installing bioperl is such a pain, it would be nice if new users didn't have to wrestle with this to run PhyloSift. We should work towards Virtual Machine and Cloud Computing options for running PhyloSift (the latter is easy after the VM compilation - Amazon cloud requires a disc image and then you can just run the software as an EC2 after booting up an instance)

**Comment by koadman** [comment]
BioPerl is already packaged with Phylosift.
