### ISSUE TITLE
Bowtie error

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#126]
Getting bow tie errors when trying to run ./phylosift all file.fasta 

Looks like a problem with the ribosomal marker index file?

Could not locate a Bowtie index corresponding to basename "/home/hollybik/share/phylosift/markers/rnadb"
Error: Encountered internal Bowtie 2 exception (#1)

**Comment by koadman** [comment]
This should be fixed, but may require deleting the existing markers and re-downloading:
`rm -rf /home/hollybik/share/phylosift/markers/`

and also downloading the latest phylosift.
