### ISSUE TITLE
all markers are being passed to all modules

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#133]
We need to keep track of which markers get hits in FastSearch.pm then only use those markers in subsequent modules.

Return from FastSearch the marker hit
OR
Grab the marker names from the blastDir from the files written directly from inside the MarkerAlign.pm module

Running with -extended takes a long time because it's gathering all 350k markers at the start of the pipeline.

**Comment by gjospin** [comment]
A rework of the extended marker DB would be needed in order to change the way markers are gathered.
Changes in the code allowed for faster execution. May not need to go through with this.

**Comment by koadman** [comment]
seems to be resolved can re-open later if needed
