### ISSUE TITLE
Bowtie paired ends

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#134]
Bowtie seems to wait for something when trying to pass it 2 paired ends files using the -1 and -2 arguments.
This stalls the octopus and prevents continuation of the pipeline.

**Comment by koadman** [comment]
Currently working around this by putting both reads into single-end bowtie run. bowtie2-align can run in paired mode with 2 fifos on the command-line, however, there seems to be a buffering deadlock when writing to the pipes from perl. It could be that single-end mode is good enough for the search phase.

**Comment by koadman** [comment]
buffer I/O deadlock between perl and bowtie2. will not fix.
