### ISSUE TITLE
alignment concatenation is too slow

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#139]
When alignments with thousands of sequences are being concatenated using bioperl's concat function, it can take days or weeks. This should only take a few seconds.

**Comment by gjospin** [comment]
How are the alignments concatenated ? Alphabetically from the PMPROK marker list ?

**Comment by koadman** [comment]
The order is given in the `alignments` array parameter to `Phylosift::Utilities::concatenate_alignments()` but is essentially arbitrary. It just needs to be the same order every time. If the order changes the DB update just needs to be run again.

However, I think the donkey cart chunking solves the speed issue because the number of sequences in the concatenation never gets very big. So I think we should close this.
