### ISSUE TITLE
identify and correct spelling and grammar errors in the web presence

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#140]
Various parts of the PhyloSift web presence contain spelling mistakes and typos. This makes our web presence appear hasty and unprofessional. For example in the google groups page phylogeny is misspelled, and on the top wordpress blog post the words data and analysis are conjoined. There are others. Related to this, it would be more professional to always use full names of project members on web sites.

**Comment by hollybik** [comment]
Oops, thanks for flagging up these mistakes. I've carefully gone through all our web outlets and corrected spelling mistakes, grammar, punctuation, etc. and used full names of project members where lacking.
