### ISSUE TITLE
Need an NCBI taxon ID list for the base euk markers

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#143]
In order to use the markers from Parfrey and the 18s markers for taxonomic summaries, we need a table that lists the sequence identifier in the alignment (e.g. FastA header ID) and the NCBI taxon ID for every sequence.

**Comment by hollybik** [comment]
NCBI has a nice tab-delmited format that links GIs with taxon IDs, but I'll have to convert the accessions from the FASTA headers for all of the Parfrey Sequences before querying, as follows:
1. Grep and trim Accession numbers from original FASTA files
2. Use Bioperl to convert Accessions to GIs, via NCBI's E-utilities
3. Match GI to taxon IDs in NCBI file "gi_taxID_prot.dmp.gz" 

Playing around with this this weekend, progress depends on how nicely the specific bioperl packages are cooperating on Edhar...

Same methodology for the 18S sequences using the nucleotide database - but where is the master 18S rep set FASTA file located?

**Comment by hollybik** [comment]
Done!!! All uploaded to Edhar!!!
