### ISSUE TITLE
improve the benchmark to report precision, recall, F1 etc

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#145]
The benchmark currently reports "accuracy" at each taxonomic level. It would ideally report precision and recall of placement, along with the F1 score. These metrics could be reported on a per-organism basis as well, and if metadata about the test organism such as its phylogenetic distance from other taxa were available, the relationship between that metadata and accuracy could be shown.

**Comment by mayalowe** [comment]
After some discussion with Aaron we're going to hold off on this for the time being in favor of more useful and less complex open issues.

**Comment by koadman** [comment]
pushed with commit 9786306 
calculation of recall for taxonomic structure estimation purposes requires special simulated data where all reads should align to markers
