### ISSUE TITLE
Modify filenames for rRNA outputs in blastDir

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#147]
At the moment, all of the filenames related to rRNA candidate sequences in the blastDir are written with an .aa extension. This is confusing for users because it conflicts with the naming conventions for the protein-coding PhyloSift markers (.aa vs .ffn)--implies that the rRNA sequences in these files are in amino acid format, when they are actually all nucleotides.

**Comment by hollybik** [comment]
Also - it is very confusing to differentiate between Bowtie and lastal outputs. I suggest we also add a .bowtie tag somewhere in the file name - e.g. clearer outputs could named be something like:
16S_bac.short.bowtie.candidate.ffn
16S_bac.long.lastal.candidate.ffn

...etc. for 16S_arc and 18S_euk candidate sequence files

**Comment by hollybik** [comment]
Yeah...more issues with rRNA files. There are "duplicate" files containing different sequences (or one file containing a subset of the other) and its not clear where each of these files are generated from. E.g. *lastal.rna.candidate.aa and *rna.long.candidate.aa  are very similar files, and in my mind they would be the same output (the long candidate sequences that get mined via lastal). same issue with the *.rna.candidate and *.short.candidate.aa duplicates presumably from Bowtie.

**Comment by koadman** [comment]
Perhaps we should evaluate whether these files are intended for public consumption. The naming scheme was a bit tricky to implement correctly and I'm not excited about making further tricky changes solely for aesthetic reasons if we don't intend this to be a primary consumable output for users. What are the use cases for these? I am concerned that the marker hits in blastDir are not fully screened, and many drop out during HMM alignment, so any use of these seems to require the filtering done in the align stage. In which case we should discourage people from snooping around in `blastDir` or at least not draw excessive attention to it in the docs.

**Comment by hollybik** [comment]
Blast directory files aren't meant for public consumption - users should be going into the align directory if they want a FASTA file of candidate sequences.
