### ISSUE TITLE
Add flag for users to specify what type of concatenated alignments get pplaced

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#148]
Guillaume says that Phylosift right now is generating a number of different concatenated alignments: amino acid alignments (PhyloSift marker genes), nucleotide alignments (Phylosift marker genes), and nucleotide + rRNA alignments. If I was a biologist I'd want to compare the placement of my input sequences across different parameters, e.g. I would want to see the .jplace files for ALL of these different concatenated alignment options. But since pplacer is such a computational suck, it might be more feasible to add the .jplace concatenated alignment option as an input flag when executing the wrapper script.

**Comment by koadman** [comment]
Umm, these get generated but only one full concat (the AA) is currently used for placement so there's no possibility to shave off compute time here. The 16s+codon is generated but currently unused, new code on the 120411_codon_placement branch uses the parts of the codon-only concat tree to do high resolution (think subspecies) placement when such data is available. However this is placement on a subtree so it's very fast, almost instant. Closing this, but we can think about reopening it if the possibility exists in the future to do placement of the same data on multiple trees of the same taxa.
