### ISSUE TITLE
Error complying got option "all"

### ISSUE THREAD

**Issue by inti** [gjospin/PhyloSift#151]
Hi,
I just downloaded the software, unpacked it, tried to run it and a I am getting the following error message. Any idea what may be wrong. 
Inti

ATALAYA:phylosift_20120417 inti$  ./phylosift.pl 
"all" is not defined in %Bio::Align::Utilities::EXPORT_TAGS at /Users/inti/Installed_Apps/EnsemblAPI/bioperl-1.2.3/Bio/Align/Utilities.pm line 10
Can't continue after import errors at /Users/inti/Installed_Apps/phylosift_20120417/bin/../lib/Phylosift/Utilities.pm line 10
BEGIN failed--compilation aborted at /Users/inti/Installed_Apps/phylosift_20120417/bin/../lib/Phylosift/Utilities.pm line 10.
Compilation failed in require at /Users/inti/Installed_Apps/phylosift_20120417/bin/../lib/Phylosift/Phylosift.pm line 12.
BEGIN failed--compilation aborted at /Users/inti/Installed_Apps/phylosift_20120417/bin/../lib/Phylosift/Phylosift.pm line 12.
Compilation failed in require at bin/phylosift line 9.
BEGIN failed--compilation aborted at bin/phylosift line 9.

**Comment by koadman** [comment]
Looks like there's an older version of BioPerl on your system that is taking precedence over the version packaged with PhyloSift.  A quick workaround is to add the version packaged with PhyloSift to the perl library path like this:

`export PERL5LIB="/Users/inti/Installed_Apps/phylosift_20120417/lib:$PERL5LIB"`

Once that's done you should be able to run phylosift from the same terminal window.
We'll investigate a more permanent fix for this issue.

**Comment by inti** [comment]
Hi,
Thanks for your quick reply. Your are right about the error's source. The bioperl installs are a bit mess up on my laptop. I have install it on our cluster and I do not get the error message any more.
Thanks again,
Best,
Inti
