### ISSUE TITLE
sequence names ending with _\d+ can not be used

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#154]
sequence names ending with _ and a number trigger buggy behavior because _\d+ is being used as a process identifier. Need to use an alternative strategy for tracking reads & search processes or make the current approach robust to this type of sequence name.

**Comment by gjospin** [comment]
I just ran a test set with ID of the form >test_\d+ and did not find issue when running the following command

./phylosift all -f -debug <filename>

Does this problem occur when a particular flag or mode is used ?

**Comment by koadman** [comment]
Perhaps we accidentally fixed it with another changeset?  Going to close but we can reopen. Also this is a good candidate for an automated perl regression test in the testing framework Eric has created.
