### ISSUE TITLE
Locate Plastid genes to add to euk marker set

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#155]
Jonathan's request...so that we can start pulling out Photosynthetic eukaryotes and cyanobacteria. The utility/issues associated with these markers will be similar to mitochondria

Cloroplast DB will be a good place to start - http://chloroplast.cbio.psu.edu/organism.cgi (probably will need to do a lot of file parsing and separating out marker genes into separate FASTA files - doesn't look like an easy way to download alignments for each gene...)

**Comment by hollybik** [comment]
Dongying has now run Markov clustering to get us some gene families - looks like we have about 200 of these for plastid genomes now. Sequences and alignments are on Merlot at:

 /share/eisen/dwu/phylosift_marker_dir/chloro_family/chloro.family.tgz

**Comment by gjospin** [comment]
Plastid markers have been added to the DB.
