### ISSUE TITLE
Scan Euk vs Bac/Arch HMMs for the 4 prospective 3-domain marker genes

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#159]
Compare profile alignments to see if we might be able to combine 4 of the eukaryotic markers with their homologs in the PMPROK bac/arch marker set. HMMs we should be comparing are as follows:

Euk Ef2 - Similarity to bac/arc Ef2 (PMPROK00060)
Euk grc5 - Similarity to bac/arc L16/L10E (PMPROK00071)
Euk rps22 - similarity to bac/arc Ribosomal Protein S8P (PMPROK00074)
Euk Rps23a - similarity to bac/arch Ribosomal Protein S12P (PMPROK00094)

**Comment by koadman** [comment]
33 of 38 PMPROK markers appear to have full length homologs in yeast
