### ISSUE TITLE
Output listing the marker genes hit per read per taxon (extra column in sequence_taxa_summary.txt)

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#169]
Taxonomy summary outputs should specifically list the marker genes which were used to inform the tree placement (e.g. which markers had data in the concatenated alignment for that taxon).  This will specifically help us to troubleshoot euk and viral placements if we can more easily see what genes are being relied upon for the placement step.

**Comment by koadman** [comment]
Done in commit 9786306
