### ISSUE TITLE
Generate test set of files to post on website alongside tutorial

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#173]
Should have some Illumina paired-end reads that users can download alongside the tutorial documentation to familiarize themselves with how phyloSift works and what outputs should be generated.

**Comment by mayalowe** [comment]
I have some paired end Illumina data that Aaron pointed me to, but bzip2 thinks the files are "corrupted".
I'm going to try to get them again and then cut them down to size.

**Comment by koadman** [comment]
Sounds like this is done.
