### ISSUE TITLE
cmalign is too slow on short sequnces

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#176]
In order to align short RNA reads correctly cmalign needs to be run with sensitive settings, e.g. --tau=1e-20. This makes it way to slow. We should consider using a different aligner for short reads.

**Comment by koadman** [comment]
create an optional alternative code path to use MUSCLE. Can do sequence to profile option, run once for each input sequence.

**Comment by koadman** [comment]
Current plan is to use hmmalign for these

**Comment by hollybik** [comment]
Duplicate issue to #254 https://github.com/gjospin/PhyloSift/issues/254
