### ISSUE TITLE
bio dataset analysis for paper: Euk Ribo OTUs

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#182]

**Comment by hollybik** [comment]
The dataset I suggest we use for Euk Ribo OTUs is my recent Molecular Ecology paper - this is deep sea data, and we did pretty extensive BLAST-based investigations of taxonomy, so I have a good idea of what things were looking like in a non-phylogenetic framework. 

Paper here: http://onlinelibrary.wiley.com/doi/10.1111/j.1365-294X.2011.05297.x/full
Data here (but have a local copy of this): http://hdl.handle.net/10255/dryad.34624

**Comment by hollybik** [comment]
Data located and ready to run - going to close this issue.
