### ISSUE TITLE
buildbot slave on a mac

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#189]
buildbot seems to be running nicely on linux, we should also add a mac buildbot slave so that all the tests can be run there too

**Comment by mayalowe** [comment]
Don't worry about that little thing that says "failed" on the waterfall display, that's only showing up because one of the packaged tests in Phylosift is failing due to lack of an unnecessary module in our code.  But it builds! (Hopefully) When we run our own test scripts we won't see fails.
