### ISSUE TITLE
'all' flag is not accepted / compilation errors?

### ISSUE THREAD

**Issue by dbrami** [gjospin/PhyloSift#192]
cmd-> /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/phylosift all --output=results_BS27 --threaded=22 --debug --paired ${DATA}/SGI_BS27.1.fastq ${DATA}/SGI_BS27.2.fastq 1>PhyloSoft.out 2>PhyloSoft.err &
[1] 9655

dbrami@asm04.c01:/tmp/PhyloSift
cmd->
[1]+  Exit 255                /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/phylosift all --output=results_BS27 --threaded=22 --debug --paired ${DATA}/SGI_BS27.1.fastq ${DATA}/SGI_BS27.2.fastq > PhyloSoft.out 2> PhyloSoft.err

dbrami@asm04.c01:/tmp/PhyloSift
cmd-> ls -lstrh
total 4.0K
   0 -rw-rw-r-- 1 dbrami employees   0 Apr 30 13:37 PhyloSoft.out
4.0K -rw-rw-r-- 1 dbrami employees 932 Apr 30 13:37 PhyloSoft.err

dbrami@asm04.c01:/tmp/PhyloSift
cmd-> cat PhyloSoft.err
"all" is not defined in %Phylosift::UpdateDB::EXPORT_TAGS at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/../lib/Phylosift/UpdateDB.pm line 5
Can't continue after import errors at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/../lib/Phylosift/MarkerBuild.pm line 5
BEGIN failed--compilation aborted at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/../lib/Phylosift/MarkerBuild.pm line 5.
Compilation failed in require at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/../lib/Phylosift/Phylosift.pm line 20.
BEGIN failed--compilation aborted at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/../lib/Phylosift/Phylosift.pm line 20.
Compilation failed in require at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/phylosift line 9.
BEGIN failed--compilation aborted at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120430/bin/phylosift line 9.

**Comment by koadman** [comment]
thanks. this should be fixed with tomorrow's build.  result of an accidental/untested commit to master. please reopen if not fixed..
