### ISSUE TITLE
Read placement using extended markers isn't happening.

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#196]

**Comment by koadman** [comment]
details? Did you remember to run with --updated_markers=0?

**Comment by gjospin** [comment]
I did not run with --updated_markers=0.
I am trying again with a recent pull.

On Tue, May 1, 2012 at 9:01 AM, Aaron Darling
reply@reply.github.com
wrote:

**Comment by gjospin** [comment]
--updated_markers=0 fixed the problem.
