### ISSUE TITLE
Persistent errors in running analysis on Devel branch

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#197]
Still getting this error so posting the issue as a bug (assigning to Guillaume since it sounds like he was making progress on similar issues). 

Error messages cropping up after deleting local markers and running ./phylosift.pl all -marker_url="http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/devel" /home/hollybik/TestData/xeno_assembly_low_cov_NameEdit.fa

Unable to find marker data!
Downloading from http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/devel/markers.tgz
Unable to find NCBI taxonomy data!
Downloading from http://edhar.genomecenter.ucdavis.edu/~koadman/ncbi.tgz
Use of uninitialized value $marker in substitution (s///) at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 1300, <$FH> line 40003.
Use of uninitialized value $marker in concatenation (.) or string at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 1301, <$FH> line 40003.
Use of uninitialized value $marker in substitution (s///) at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 1300, <$FH> line 40003.
Use of uninitialized value $marker in concatenation (.) or string at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 1301, <$FH> line 40003.
Missing required argument marker at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 79
        Phylosift::Utilities::miss('marker') called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 587 
        Phylosift::Utilities::get_marker_path('marker', undef) called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Utilities.pm line 802
        Phylosift::Utilities::is_protein_marker('marker', undef) called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/MarkerAlign.pm line 205
        Phylosift::MarkerAlign::markerPrepAndRun('self', 'Phylosift::Phylosift=HASH(0x20a5d48)', 'marker_reference', 'ARRAY(0x32a7420)', 'chunk', 1) called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/MarkerAlign.pm line 73
        Phylosift::MarkerAlign::MarkerAlign('self', 'Phylosift::Phylosift=HASH(0x20a5d48)', 'marker_reference', 'ARRAY(0x39c9e68)', 'chunk', 1) called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/FastSearch.pm line 100
        Phylosift::FastSearch::run_search('self', 'Phylosift::Phylosift=HASH(0x20a5d48)', 'marker_reference', 'ARRAY(0x39c9e68)') called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Phylosift.pm line 457
        Phylosift::Phylosift::run_search('self', 'Phylosift::Phylosift=HASH(0x20a5d48)', 'cont', 0, 'marker', 'ARRAY(0x39c9e68)') called at /home/hollybik/phylosift_devel_20120501/bin/../lib/Phylosift/Phylosift.pm line 164
        Phylosift::Phylosift::run('Phylosift::Phylosift=HASH(0x20a5d48)', 'force', 0, 'custom', undef, 'cont', 0) called at bin/phylosift line 156

**Comment by gjospin** [comment]
I think we will have to do an in person test run, @koadman and myself can't seem to reproduce the error.

**Comment by hollybik** [comment]
I'm running this on Edhar - unpacked devel bundle this morning into /home/hollybik/phylosift_devel_20120501/  xeno data is in /home/hollybik/TestData/xeno_assembly_low_cov_NameEdit.fa

I will try to run it again now but otherwise we can debug in person tomorrow morning.

**Comment by koadman** [comment]
Should be fixed with commit 442f7de
