### ISSUE TITLE
"version.txt" in markers?

### ISSUE THREAD

**Issue by dbrami** [gjospin/PhyloSift#199]
I just downloaded a fresh copy of the markers.tgz, hoping it would solve this error, with no luck:

Unable to read from /home/dbrami/share/phylosift/markers/version.txt at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120502/bin/../lib/Phylosift/Utilities.pm line 92
        Phylosift::Utilities::ps_open('/home/dbrami/share/phylosift/markers/version.txt') called at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120502/bin/../lib/Phylosift/Utilities.pm line 237
        Phylosift::Utilities::get_marker_version('path', '/home/dbrami/share/phylosift/markers') called at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120502/bin/../lib/Phylosift/Utilities.pm line 289
        Phylosift::Utilities::marker_update_check('self', 'Phylosift::Phylosift=HASH(0x18dde2a0)', 'dir', '/home/dbrami/share/phylosift/markers', 'url', 'http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_mark...') called at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120502/bin/../lib/Phylosift/Utilities.pm line 347
        Phylosift::Utilities::data_checks('self', 'Phylosift::Phylosift=HASH(0x18dde2a0)') called at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120502/bin/../lib/Phylosift/Phylosift.pm line 150
        Phylosift::Phylosift::run('Phylosift::Phylosift=HASH(0x18dde2a0)', 'force', 0, 'custom', 'undef', 'cont', 0) called at /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120502/bin/phylosift line 156

**Comment by koadman** [comment]
We may need a bit more info to help you on this one. Can you tell us whether you're using the devel branch build of phylosift or the master branch? Also, can you try deleting the marker directory first:
`rm -rf /home/dbrami/share/phylosift/markers`
and re-running phylosift?
phylosift currently creates the version.txt after downloading the markers itself, so if you downloaded them manually and unpacked them, that file would not get created.

**Comment by koadman** [comment]
Upon further investigation we discovered an accidental commit to the master branch which broke phylosift last week. This has been resolved and master appears to be working again.  Sorry!! We nearly have an automated test suite ready that will catch issues like this in the future. Closing for now, but please reopen if the issue persists.

**Comment by dbrami** [comment]
so if i download a new master copy of program, unpack and run, the error
should not persist, right?

On Wed, May 2, 2012 at 5:11 PM, Aaron Darling <
reply@reply.github.com

**Comment by koadman** [comment]
hopefully not. master was rebuilt this afternoon and passed the
benchmark test successfully. the benchmark doesn't run through all code
paths though, so you might still have problems with an untested part of
the code.

**Comment by dbrami** [comment]
Hi Aaron - I dont have your regular email so simply responding to this git
issue;
I am trying to do some alignments using Mauve and notice you are the lead
author.
I have tried both the windows and unix command line:

java -Xmx1500m -cp /bioinformatics/asm/bio_bin/Mauve_2.3.1/Mauve.jar
org.gel.mauve.contigs.ContigOrderer -output MauveAlign -ref
Caulobacter_crescentus_CB15_chromosome_mod.gb -draft A15A05_clc_de_novo.fa &

but the NCBI genbank files have no sequence past the origin tag.
An attempt using a fata file yielded same result - a java.io exception

Do you have a strong checklist / recipe for getting the aligner to work?

On Wed, May 2, 2012 at 7:11 PM, Aaron Darling <
reply@reply.github.com

**Comment by koadman** [comment]
please email me at aarondarling (at) ucdavis (dOt) edu
