### ISSUE TITLE
donkey cart needs to run through summarize

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#202]
currently the donkey cart runs only through pplacer. we should also have it run summarize. this could simply rerun the entire summary on all chunks, the extra compute time will probably be negligible. this will also enable deletion of the read name mapping at each donkey iteration.

**Comment by gjospin** [comment]
This should be ready to merge and close.

**Comment by koadman** [comment]
@gjospin is this merged?  if so can you close?

**Comment by gjospin** [comment]
I am seeing the changes inside summarize.pm.  Also I thought you had merged it already.
Anyways, closing.
