### ISSUE TITLE
Failed run from May 7th 2012 download.

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#203]
I received the following email: 
My first thought was that the lib directory for PS wasn't added to the perl path. But I noticed that it is ( "/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../lib"). So I am not quite sure what went wrong there.

I have downloaded phylosift. However, I had a problem to run. I am not
sure if it is my problem or not. The following is what I see:

[xiaoy@submit-1 phylosift_20120507]$ r
total 72
drwxrwxr-x+  2 xiaoy lid_users  8192 May  7 07:06 writing/
-rw-rwxr--+  1 xiaoy lid_users 12703 May  7 07:06 README*
-rw-rwxr--+  1 xiaoy lid_users   976 May  7 07:06 phylosiftrc*
-rw-rwxr--+  1 xiaoy lid_users    19 May  7 07:06 phylosift.pl*
drwxrwxr-x+  3 xiaoy lid_users  8192 May  7 07:06 osx/
drwxrwxr-x+  2 xiaoy lid_users  8192 May  7 07:06 bin/
drwxrwxr-x+ 10 xiaoy lid_users  8192 May  7 07:07 lib/
drwxrwxr-x+  4 xiaoy lid_users  8192 May  7 07:07 legacy/
[xiaoy@submit-1 phylosift_20120507]$ cd bin
[xiaoy@submit-1 bin]$ r
total 56104
-rwxrwxr--+ 1 xiaoy lid_users     828 May  7 07:06 taxit*
-rwxrwxr--+ 1 xiaoy lid_users 1292176 May  7 07:06 segment_tree*
-rwxrwxr--+ 1 xiaoy lid_users 6631842 May  7 07:06 rppr*
-rwxrwxr--+ 1 xiaoy lid_users 1748988 May  7 07:06 readconciler*
-rwxrwxr--+ 1 xiaoy lid_users 1829752 May  7 07:06 raxmlHPC*
-rwxrwxr--+ 1 xiaoy lid_users 1308560 May  7 07:06 print_splits*
-rwxrwxr--+ 1 xiaoy lid_users 6868805 May  7 07:06 pplacer*
-rwxrwxr--+ 1 xiaoy lid_users    6868 May  7 07:06 phylosift*
-rwxrwxr--+ 1 xiaoy lid_users 9292180 May  7 07:06 pda*
-rwxrwxr--+ 1 xiaoy lid_users 1382384 May  7 07:06 lastdb*
-rwxrwxr--+ 1 xiaoy lid_users 1685520 May  7 07:06 lastal*
-rwxrwxr--+ 1 xiaoy lid_users 1503784 May  7 07:06 hmmsearch*
-rwxrwxr--+ 1 xiaoy lid_users 1481192 May  7 07:06 hmmbuild*
-rwxrwxr--+ 1 xiaoy lid_users 1436520 May  7 07:06 hmmalign*
-rwxrwxr--+ 1 xiaoy lid_users 7342541 May  7 07:06 guppy*
-rwxrwxr--+ 1 xiaoy lid_users    1030 May  7 07:06 grinder*
-rwxrwxr--+ 1 xiaoy lid_users  315485 May  7 07:06 FastTree*
-rwxrwxr--+ 1 xiaoy lid_users 2090552 May  7 07:06 cmalign*
-rwxrwxr--+ 1 xiaoy lid_users 3384399 May  7 07:06 bowtie2-build*
-rwxrwxr--+ 1 xiaoy lid_users 7763361 May  7 07:06 bowtie2-align*

Everything looks fine in the directory.

However, when I run it, it gave me an error message as following:

[xiaoy@submit-1 bin]$ ./phylosift
Can't locate Locale/Maketext/Simple.pm in @INC (@INC contains:
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../osx/darwin-thread-multi-2level/
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../legacy/
/usr/local/bio_apps/perl/lib/site_perl/5.12.1
/usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi
/usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl
/usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi
/usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl
/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8
. /hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../lib) at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../osx/darwin-thread-multi-2level//IPC/Cmd.pm
line 47.
BEGIN failed--compilation aborted at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../osx/darwin-thread-multi-2level//IPC/Cmd.pm
line 47.
Compilation failed in require at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../osx/darwin-thread-multi-2level//File/Fetch.pm
line 13.
BEGIN failed--compilation aborted at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../osx/darwin-thread-multi-2level//File/Fetch.pm
line 13.
Compilation failed in require at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../lib/Phylosift/Utilities.pm
line 17.
Compilation failed in require at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../lib/Phylosift/Phylosift.pm
line 12.
BEGIN failed--compilation aborted at
/hpc2/lid/lid_data/xiaoy/bin/phylosift_20120507/bin/../lib/Phylosift/Phylosift.pm
line 12.
Compilation failed in require at ./phylosift line 9.
BEGIN failed--compilation aborted at ./phylosift line 9.

Did I do something wrong or I need to set other things?

**Comment by koadman** [comment]
Looks like it needs Locale::Maketext::Simple. Added to packaging in commit 9745653
