### ISSUE TITLE
Compilation fail?

### ISSUE THREAD

**Issue by ewilbanks** [gjospin/PhyloSift#212]
Hey there lovely phylosifty labmates,

I'm running Phylosift on my Mac OSX 10.6 desktop 64bit for the first time and get this error.  Is it you or is it me?

$ ./phylosift.pl all scaffolds_interleaved_ill_w454.fa 
Attempt to reload LWP/UserAgent.pm aborted.
Compilation failed in require at /Users/ewilbanks/phylosift_20120519/bin/../lib/LWP/Simple.pm line 26.
BEGIN failed--compilation aborted at /Users/ewilbanks/phylosift_20120519/bin/../lib/LWP/Simple.pm line 26.
Compilation failed in require at /Users/ewilbanks/phylosift_20120519/bin/../lib/Phylosift/Utilities.pm line 14.
BEGIN failed--compilation aborted at /Users/ewilbanks/phylosift_20120519/bin/../lib/Phylosift/Utilities.pm line 14.
Compilation failed in require at /Users/ewilbanks/phylosift_20120519/bin/../lib/Phylosift/Phylosift.pm line 12.
BEGIN failed--compilation aborted at /Users/ewilbanks/phylosift_20120519/bin/../lib/Phylosift/Phylosift.pm line 12.
Compilation failed in require at bin/phylosift line 9.
BEGIN failed--compilation aborted at bin/phylosift line 9.

**Comment by mayalowe** [comment]
This looks like it might be on your end (Aaron or Guillaume can correct me if I'm mistaken here), but not to worry! There's a perl module that Phylosift needs to run and you either don't have it on your computer or it's not in your perl path.  
At the command line, type perl -V, which should list the directories where perl will look for modules.  Check through the listed directories and see if you have a folder named LWP.  If not, you can install it using CPAN or by going here: http://search.cpan.org/~gaas/libwww-perl-6.04/lib/LWP/Simple.pm

**Comment by ewilbanks** [comment]
Yay- that fixed it!  Thanks Eric.
