### ISSUE TITLE
BioPython and binary impediments for build_marker workflow

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#216]
build_marker mode is currently aborting on Edhar because of issues with BioPython, and also not running on Mac OSX because at least PDA and FastTree binaries aren't specifically compiled for Mac (may be more issues with other binaries too)

**Comment by koadman** [comment]
Mac versions of pda, FastTree, and readconciler have been added. `taxit` has many dependencies that we can not package with phylosift, so users will be required to install this themselves. A check for taxit has been added to the marker build and if not found, a message is printed instructing users to download it.
