### ISSUE TITLE
Reinstate --extended marker flag in the --help dialogue

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#218]
This option seems to be deleted from the help dialogue in the devel branch (haven't checked master)

**Comment by mayalowe** [comment]
--extended and the other options were in the README, but weren't in /bin/phylosift.  I added --extended, and I'm going to make sure that the other options are present in the help dialogue as well and add as needed.

**Comment by hollybik** [comment]
Yep, just double checked this in the latest overnight build of the devel branch, and the --extended option is back up and running!
