### ISSUE TITLE
Fix the custom marker feature

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#219]
Custom marker lists don't seem to be working at the moment - looks like it fails at the fast candidate search (temporary LAST files weren't deleted from the blastDir)

**Comment by gjospin** [comment]
This feature seems to work  again.
Need to use the BASENAME for the markers (ie PMPROK00094) and not the ones with .update or .codon added.

Also added some code to prevent writing output in the blastDir for the markers not present in the custom file
