### ISSUE TITLE
make a very simple web interface

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#220]
The web interface would ideally take one or more fastq files as input, transfer a part of these from the user's computer to the server, and process a few chunks. After each chunk completes the user's browser would ideally refresh with the updated krona plot.

**Comment by mayalowe** [comment]
Doesn't take files yet, but here is the first decent prototype of the interface: http://edhar.genomecenter.ucdavis.edu/~elowe/

**Comment by mayalowe** [comment]
Web interface now supports uploading files. Note: I've disabled this on the live interface because I still have to add in a lot of checks and security things.  Small text files were able to be written to a [named pipe](http://en.wikipedia.org/wiki/Named_pipe).

**Comment by mayalowe** [comment]
I think this is working. It can be prettier, but it works!
