### ISSUE TITLE
Summary output file listing final # of candidate sequences pulled down for each marker

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#228]
Right now there's no output file which lists the final number of candidate sequences which have been pulled down for each marker - the only way I can find this information out is by manually looking in the alignDir files. It would be great to have one file listing all the markers found in an analysis, and the number of corresponding candidate sequences matching each marker.

There are so many markers now that the outputs are getting overwhelming to browse -- knowing the most abundant marker (e.g. the viral marker that got the most hits) would make it much easier to look through the data.

**Comment by gjospin** [comment]
PS creates a new file labeled "marker_summary.txt" that lists all the markers that were hit and the number of hits associated to them (according to the sequence summary files).
