### ISSUE TITLE
Taxit doesn't recognize -Y

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#230]
Taxit fails when given the -Y argument.  Formerly needed to specify FastTree.

Maybe the new taxit version automatically recognizes Fasttrees.

**Comment by gjospin** [comment]
I have updated MarkerBuild.pm and UpdateDB.pm. Waiting for confirmation about the new behavior from @koadman to push

**Comment by koadman** [comment]
Before we push this we need to update the taxit on merlot, otherwise the ongoing marker builds are going to fail. There's a marker build running right now so would be nice to wait til it completes.

**Comment by gjospin** [comment]
Just let me know when things finish.

**Comment by koadman** [comment]
ok, updated taxit is on merlot now too. safe to close i think.
