### ISSUE TITLE
Bowtie shared library

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#231]
Attempting to run assembled contigs through PS and got the following error :

/home/gjospin/git/PhyloSift/bin/bowtie2-align: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

This problem is from trying to load the 32bit executable from a 64 bit environment however they don't use the same libraries.

Running the following command fixed my problem <code>sudo apt-get install libstdc++6:i386</code> but it may be better to distribute the 64 bit version if it is available.

**Comment by koadman** [comment]
A 64-bit bowtie was added with commit 55149da75cc97b9fac69cb130db814f844b8e10e and should resolve this issue.
