### ISSUE TITLE
Occasional error reading phred33 fastq data across chunks

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#235]
When using phred33 fastq data, the quality score lines will occasionally start with `@`. The code in FastSearch.pm currently looks for `@` to indicate the start of a new sequence entry. This code can mistakenly recognize a quality string as the beginning of a new record after the first chunk has finished processing.

**Comment by gjospin** [comment]
I got this problem too. I also had forgotten to add the -paired flag
which ended up fixing the problem.

On Sat, Jun 9, 2012 at 4:17 AM, Aaron Darling
reply@reply.github.com
wrote:
