### ISSUE TITLE
perl is sad

### ISSUE THREAD

**Issue by ryneches** [gjospin/PhyloSift#236]
Following the README...

[russell@compute-2-7 phylosift_20120610 ]$ ./phylosift.pl all --output=results --paired /share/eisen-d1/illumina_data/dhs/Russell_34.r1.fastq.gz /share/eisen-d1/illumina_data/dhs/Russell_34.r2.fastq.gz  
Can't locate HTTP/Date.pm in @INC (@INC contains: /home/russell/pkg/phylosift_20120610/bin/../legacy/ /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 . /home/russell/pkg/phylosift_20120610/bin/../lib) at /home/russell/pkg/phylosift_20120610/bin/../lib/LWP/Simple.pm line 28.  
BEGIN failed--compilation aborted at /home/russell/pkg/phylosift_20120610/bin/../lib/LWP/Simple.pm line 28.  
Compilation failed in require at /home/russell/pkg/phylosift_20120610/bin/../lib/Phylosift/Utilities.pm line 14.  
BEGIN failed--compilation aborted at /home/russell/pkg/phylosift_20120610/bin/../lib/Phylosift/Utilities.pm line 14.  
Compilation failed in require at /home/russell/pkg/phylosift_20120610/bin/../lib/Phylosift/Phylosift.pm line 12.  
BEGIN failed--compilation aborted at /home/russell/pkg/phylosift_20120610/bin/../lib/Phylosift/Phylosift.pm line 12.  
Compilation failed in require at bin/phylosift line 9.  
BEGIN failed--compilation aborted at bin/phylosift line 9.

**Comment by koadman** [comment]
With a little luck this was resolved with commit 4a95339. However, there may be other missing dependencies, I am unable to test. A new devel branch build will be appearing in the next hour or so, can you check whether this resolves the issue for you and if so close?

**Comment by hollybik** [comment]
This was similar to an e-mail issue we recently received -- need to document this on the Google Support forum since other users are having this issue

**Comment by hollybik** [comment]
Summarized this error and posted fix instructions for users in the PhyloSift Google Group forum:
https://groups.google.com/forum/?fromgroups#!topic/phylosift/7seeMIvx51I%5B1-25%5D

Seems to be resolved after the Date.pm module is installed, so closing this issue now.
