### ISSUE TITLE
Document accepted file formats

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#237]
Accepted file formats : 
Fasta
paired fasta (using -paired <file1> <file2>)
interleaved paired fasta (-paired <file1>)
fastq (same as fasta but with quality scores)
interleaved fastq (same as fasta but with quality scores)
<any file format>.gz (compressed file using gzip)
<any file format>.bz (compressed file using bzip)

Special behavior for issue #214

Users can use -paired and specify 1 or 2 files. If they specify 2 files, we are assuming (according to format guidelines) that each file contains an entry for each molecule. So we have both reads for each pair.
The interleaved format, the user would specify only 1 file, doesn't necessarily have 2 entries per pair. Technically the 2 pairs should be read 1 after the other but I'm not sure of that. The code has been modified recently so that NOT having 2 entries per pair would break the ID mapping.

The following is an example of how reads can be arranged in an interleaved fastq file. Missing reads are due to quality filterings that would take place prior to PS processing.

<code>>read1/1</code>
<code>>read1/2</code>
<code>>read2/2</code>
<code>>read3/1</code>
<code>>read4/1</code>
<code>>read4/2</code>

All in all, I am just saying that somewhere in the Docs we should specify that both ends of a read should be submitted when using the interleaved fastq format.

**Comment by hollybik** [comment]
File formats updated on our website Documentation (http://phylosift.wordpress.com/tutorials/running-phylosift/phylosift-overview/ ) and also committed changes to the README file on devel branch.
