### ISSUE TITLE
Pplacer hangup

### ISSUE THREAD

**Issue by dbrami** [gjospin/PhyloSift#243]
Hi,

I have not been able to get Phylosift to run to completion.
At the moment, it hangs at the pplacer stage; it was processing for over a day with no progress, simply taking up memory but not using any CPU.
Have you come across this issue before? Any ideas on how to get to go through this stage?

Here is a ps aux of pplacer process:

dbrami    5139  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5140  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5141  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5142  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5143  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5144  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5145  3.1  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5146  3.1  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5147  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5148  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5149  2.9  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5150  3.2  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5151  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5152  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5153  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5154  3.2  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5155  3.1  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5156  3.0  2.9 8639700 8635568 pts/10 S   09:54   0:07 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5178 10.1  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5179 10.3  2.8 8517516 8513508 pts/10 S   09:54   0:23 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5180 10.2  2.8 8517516 8513508 pts/10 S   09:54   0:23 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5181 10.3  2.8 8517516 8513508 pts/10 S   09:54   0:23 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5182 10.4  2.8 8517516 8513508 pts/10 S   09:54   0:23 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5183  9.9  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5184  9.9  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5185 10.0  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5186 10.0  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5187 10.0  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami    5188 10.0  2.8 8517516 8513508 pts/10 S   09:54   0:22 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta
dbrami   32298  0.3  2.9 8639700 8636768 pts/10 S   Jun19   3:56 /bioinformatics/asm/bio_bin/Phylosift/phylosift_20120619/bin/pplacer --groups 10 --verbosity 0 -j 22 -c /home/dbrami/share/phylosift/markers/concat.updated my_results/alignDir/concat.1.fasta

**Comment by koadman** [comment]
It looks like you have requested 22 threads, however your system doesn't have enough memory to run 22 different pplacer threads at once. So the 22 threads start but can't make any progress because they are thrashing the computer's swap disk.

A simple solution is to restart the run with only a few threads. We currently estimate pplacer will need about 3GB memory per thread for the genes present in the phylosift databases.

**Comment by dbrami** [comment]
Ok - I will try 8 threads and let you know how it goes.
Thanks Aaron.

**Comment by dbrami** [comment]
Ok - I will try 8 threads and let you know how it goes.
Thanks Aaron.

**Comment by koadman** [comment]
Did reducing the thread count work for you? Can I close this issue?

**Comment by dbrami** [comment]
Reducing the thread count did in fact help - thanks.
You may close the issue.
