### ISSUE TITLE
crash after 10 days

### ISSUE THREAD

**Issue by dbrami** [gjospin/PhyloSift#246]
After running for over a week and a half, Phylosift crashed this morning with the following message:

--------------------- WARNING ---------------------
MSG: Replacing one sequence [GWZHISEQ01_64_D0MB2ACXX_3_2308_17604_156379/1-96]

---

Fatal error: exception Failure("the reference package provided does not contain a tree")

Is this run-time typical of a 16M read paired-end library?

**Comment by koadman** [comment]
This error message was generated by pplacer and indicates that pplacer was unable to place reads on a particular tree in the phylosift database, however, phylosift will continue to place reads on the other trees even if one fails. If you haven't Ctrl+C'd phylosift then it's either still running or has finished and produced output.

**Comment by dbrami** [comment]
I will look for result files. But what typical run times, can you give any
sort ballpark figure on typical runtimes based on various sized datasets?

On Wed, Jun 27, 2012 at 10:45 AM, Aaron Darling <
reply@reply.github.com

**Comment by koadman** [comment]
10 days seems a bit long but not impossible. The running time depends on many factors including the compute hardware and the memory but also the revision of the code used and the database. Several of our recent changes have added some very useful features at the expense of speed so it may not be as fast as it used to be. We plan to work on speedups in the July development sprint, so stay tuned.
