### ISSUE TITLE
Update markers to use Dongying's chosen 40

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#247]
Currently we use 38 core PMPROK markers, however Dongying has added and removed a few to make a set of 40 that he will publish. We should update our core marker set to match his published set. At the same time we can get rid of the old marker format (yay!)

**Comment by gjospin** [comment]
Data has been downloaded and prepped for PS marker_build mode. Will run soon.

The 40 core markers's new name will be DNGNGWU#####.  The code will need to be modified to reflect this change (away from PMPROK).

**Comment by gjospin** [comment]
Assigning this to Aaron to run a DB update on the new markers.

**Comment by koadman** [comment]
Done! at last! new devel markers are available from edhar. yippee!
