### ISSUE TITLE
Summary outputs and Krona file not being generated for genome contigs

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#257]
Tried running the full genome contig of B.anthracis through PhyloSift - marker gene reads are pulled out in alignDir and blastDir, but the taxonomic summary outputs and krona outputs are empty.

on Edhar: 
/home/hollybik/phylosift_master_20120717/PS_temp_B_anthracis_genome.fasta

**Comment by koadman** [comment]
This appears to be an issue with isolate assemblies not working properly unless --besthit is used. There are multiple copies/paralogs of some genes and they are not being assigned paralog IDs but instead the concatenate sequence ends up growing too long.

**Comment by koadman** [comment]
should be fixed with commit 5cb583c
