### ISSUE TITLE
PhyloSift is hogging memory on raw Illumina xeno data (13 chunks)

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#259]
Was running master branch on Edhar using the raw Illumina xeno data, and it ended up using 50% memory for processing 13 chunks. Not sure what is causing this memory, office conversation suggests that we're pulling along too much information, and/or can concatenate the summary file chunks.

Path on Edhar: /home/hollybik/phylosift_master_20120718/PS_temp/xeno_raw_s_2_1_sequence.txt

**Comment by gjospin** [comment]
This happens because PS merges sequence_taxa.<chunk>.txt files.  Large input files will yield lots of hits which will then fill up the memory when merging previous chunks' data.

**Comment by gjospin** [comment]
Fixed and pushed.  May need to reopen when @hollybik tests the 13 chunks again.
