### ISSUE TITLE
Implement Infernal to align rRNA seqs to reference alignment

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#26]

**Comment by gjospin** [comment]
Search, Aligning and Pplacer work on RNA stuff.  Taxonomy assignment needs work.

Unable to read file /home/gjospin/share/amphora2/markers/16s_reps_bac.ncbimap
 at /home/gjospin/projects/Amphora-2/lib/Amphora2/Amphora2.pm line 343
