### ISSUE TITLE
Error message: Use of uninitialized value $ncbi_name in concatenation (.) or string

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#260]
Regardless of dataset, we're running into persistent error messages related to NCBI taxonomy:

Use of uninitialized value $ncbi_name in concatenation (.) or string at /home/hollybik/phylosift_master_20120718/bin/../lib/Phylosift/pplacer.pm line 457.

Need to figure out if this is an urgent issue (returning erroneous results to users), or if it is just more annoying (since it isn't preventing users from getting _any_ output. We still get summary files and krona plots).

**Comment by gjospin** [comment]
Taxon IDs 30314, 651671, 8430 have empty taxon info when reading internal tree nodes.

These are the ones appearing using the HMP tutorial data.  It wouldn't be surprising to see other taxa show up in the same way when hits get placed to other parts of trees.  Skipping the concatenation of $node_name .= "_$ncbi_name"."_" removes the error when the taxon info doesn't exists but I am not sure this is what we want.

**Comment by gjospin** [comment]
Fixed and pushed to Devel.
