### ISSUE TITLE
Fatal errors in taxon naming: "Ref trees not the same", "sequence doesn't overlap"

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#266]
Scary error message when running the PE xeno raw data:

Naming taxa in marker concat
Running /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20120721/bin/../osx/pplacer  --verbosity 0 -j 1 -c /Users/hollybik/share/phylosift/markers/concat.codon.updated.sub22 "/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20120721/PS_temp/xeno_raw_s_2_1_sequence.txt/alignDir/concat.codon.updated.sub22.11.fasta"
Uncaught exception: Failure("Sequence HWI_ST611_0213_2_1104_19014_151773_0 doesn't overlap any reference sequences.")
Fatal error: exception Failure("Sequence HWI_ST611_0213_2_1104_19014_151773_0 doesn't overlap any reference sequences.")
Running /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20120721/bin/../osx/pplacer  --verbosity 0 -j 1 -c /Users/hollybik/share/phylosift/markers/concat.codon.updated.sub99 "/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20120721/PS_temp/xeno_raw_s_2_1_sequence.txt/alignDir/concat.codon.updated.sub99.11.fasta"
Uncaught exception: Failure("Reference trees for xeno_raw_s_2_1_sequence.txt.naming and xeno_raw_s_2_1_sequence.txt not the same! Were these run with the same reference tree and model parameters (e.g. statistics files?)")
Fatal error: exception Failure("Reference trees for xeno_raw_s_2_1_sequence.txt.naming and xeno_raw_s_2_1_sequence.txt not the same! Were these run with the same reference tree and model parameters (e.g. statistics files?)")

**Comment by koadman** [comment]
This shouldn't be happening anymore, at least not on devel with devel markers, and that is where our future lies.
