### ISSUE TITLE
Missing LWP::UserAgent when users try to run PhyloSift

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#269]
See recent e-mail from Marisa about library issues

**Comment by koadman** [comment]
Not able to reproduce this error.

**Comment by koadman** [comment]
Guillaume just found possibly the same issue on merlot, now digging into it!

**Comment by koadman** [comment]
This looks to be resolved on merlot when running in client mode (not dbpudates). I am going to close because I haven't been able to reproduce on Mac, but may need to reopen if it resurfaces.
