### ISSUE TITLE
Testing of PhyloSift with Extended Markers

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#272]

**Comment by mayalowe** [comment]
Ran PhyloSift with Extended markers on simulated Uniform Illumina dataset and benchmarked output/compared with MEGAN.  Running extended markers on Simulated Exponential Illumina data (should be done by week's end) and will benchmark output/compare with MEGAN once it is finished.

**Comment by mayalowe** [comment]
Benchmarked and compared with MEGAN for both datasets!
