### ISSUE TITLE
Bug in --paired sequence merging

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#277]
When using the phylosift tutorial data, it seems that sequence names are not being correctly recognized and all hits are getting merged to a single sequence.

**Comment by koadman** [comment]
Digging deeper on this issue: Guillaume was unable to replicate it, I was unable to replicate on a separate machine. Appears to be a configuration-specific problem on my laptop.

**Comment by koadman** [comment]
I have narrowed the bug down to the case where input files contain a mix of reads with and without /\d read identifiers, e.g. the /1 and /2 that some Illumina files have. When a mix exists, all reads within a marker are getting merged. This is happening on master.

**Comment by gjospin** [comment]
Is the mix within a pair such that we'd have ID/1 and ID or is it consistent across each pair ?
The sequence demultiplexer from FastSearch.pm adds /1 and /2 if the IDs are the same. If they aren't (with /1 and /2) then they should just go on normally.  This is done on a per pair basis.

**Comment by gjospin** [comment]
So I think I have reproduced the problem.

When 1 read of the pair does not have the /1 or /2 then the reads without the /\d gets dumped into a read named after the input filename.

**Comment by gjospin** [comment]
Pushed a solution to Master.

**Comment by gjospin** [comment]
Re-opening. Got a file from Aaron that breaks this again.

**Comment by gjospin** [comment]
This is fixed enough for this issue.
Will need to open another issue for checks or mapping of reads when mates are missing.
