### ISSUE TITLE
* in the sequences breaks build_marker

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#285]
Having \* characters in the sequences breaks build_marker because Fasttree outputs an empty tree saying the sequences are not the same lengths.

Possible work around (what I did with Lizzy's data set) is to replace the \* by -

**Comment by koadman** [comment]
If the input is DNA then \* should not be allowed, period. phylosift and other programs should throw an error. when input is protein, \* is sometimes used to indicate stop codons. In other parts of the code our strategy has been to translate these to X (e.g. unknown amino acid) so we can tolerate noisy data with erroneous stop codons.

**Comment by gjospin** [comment]
Added a sequence integrity function.  We can append new checks as we come across them.
So far the only thing that croaks is the presence of \* in DNA sequences.
- in proteins gets translated to Xs.
  Pushed to Devel.
  Closing.
