### ISSUE TITLE
Devel branch align step is broken

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#286]
I get the same error when running. The input type is Protein.

> ./phylosift.pl all -f --debug --stdin test_stream < sample_seq/num_test.faa
> OR
> ./phylosift.pl all -f --debug sample_seq/num_test.faa

Assigning to Aaron for now as I suspect it is related to the code added for streaming.  Will take a look and see what I can do as well.

after HMMSEARCH PARSE
Running /home/gjospin/git/PhyloSift/bin/hmmalign --outformat afa --mapali /home/gjospin/share/phylosift/markers/PMPROK00087.stk /home/gjospin/share/phylosift/markers/PMPROK00087.hmm "/home/gjospin/git/PhyloSift/PS_temp/num_test.faa/alignDir/PMPROK00087.newCandidate.aa.1" |
readline() on unopened filehandle at /home/gjospin/git/PhyloSift/lib/Phylosift/Utilities.pm line 1783.
TYPE : dna
MARKER : PMPROK00087

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: cannot find Test_2757
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.14.2/Bio/Root/Root.pm:368
STACK: Phylosift::MarkerAlign::aa_to_dna_aln /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:417
STACK: Phylosift::MarkerAlign::alignAndMask /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:605
STACK: Phylosift::MarkerAlign::MarkerAlign /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:73
STACK: Phylosift::FastSearch::run_search /home/gjospin/git/PhyloSift/lib/Phylosift/FastSearch.pm:140
STACK: Phylosift::Phylosift::run_search /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:580
STACK: Phylosift::Phylosift::run /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:193

**Comment by koadman** [comment]
should be fixed with commit 5049610. there was a straggling call to get_input_sequence_type(). thanks for spotting this!
