### ISSUE TITLE
.taxonmap files missing from 16s and 18s

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#288]
Trying to figure out why we didn't get summaries for 16s or 18s markers, I realized we don't have the taxonmap files in the 16s and 18s directories.

Those are available on edhar. I will package get them on edhar@/home/koadman/phylosift/R_taxonmap/

**Comment by gjospin** [comment]
I repackaged the 16s bac and arc and 18S markers. 
They are available on edhar @ /home/koadman/phylosift/R_taxonmap/marker_build_ribosomal_markers.tar.gz

These newly packaged markers should work with the hmmalign change from master.  All that needs to be done now is add them to the downloadable DB.

**Comment by hollybik** [comment]
Closing because they've been uploaded to edhar
