### ISSUE TITLE
Phylosift Benchmark reporting > 100% Accuracy for certain taxonomic levels

### ISSUE THREAD

**Issue by mayalowe** [gjospin/PhyloSift#293]
This happens with both MEGAN and Phylosift output, but for the Species rank and the "No Rank" rank PS reports accuracy greater than 100%, around 145% for species and between 108 and 120% for No Rank.

**Comment by koadman** [comment]
This is because "No Rank" can appear multiple times in a taxonomic path, e.g. between Phylum and Family, and again below Species. Suggested fix is to remove reporting for "No Rank" in phylosift benchmark output.
