### ISSUE TITLE
--extended mode Summary.pm not working properly

### ISSUE THREAD

**Issue by mayalowe** [gjospin/PhyloSift#301]
Essentially 124k reads are being aligned but only 1542 reads are being "assigned" according to sequence_taxa.txt. 
_cracking the whip_

**Comment by koadman** [comment]
A bit more context: this is happening when processing reads with --extended. There are around 200k reads in the input set, of which around 124k make it all the way through placement onto reference trees. Only a small fraction of these appear in the taxonomic summaries.

**Comment by mayalowe** [comment]
I'm struggling with my words today.  Thanks for adding the context!

**Comment by gjospin** [comment]
This could be because a lot of extended families never finished their
marker_build steps. So the taxonomic reconcilation may not have happened
correctly if at all, so the summary which uses the taxonmap file (that
didn't get created) fails.

**Comment by koadman** [comment]
This issue appears not to be a bug in phylosift but rather that some files were accidentally not copied or deleted when moving data from one machine to another.
