### ISSUE TITLE
updateDB may be missing some published genome sequences when mining from NCBI

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#303]
It seems as if some published genome sequences aren't being mined from NCBI - for example, we can't find the published Leucobacter sequence in the Phylosift marker packages (taxon ID isn't listed in the gene_ids.aa.txt file, or in the downloaded genomes directory).  

Need to figure out if this is a specific problem with this particular genome, or if it is a more widespread problems (e.g. we're missing some genomes because of the way they're organized in NCBI).

Genome page for the missing Leucobacter genome is here: http://www.ncbi.nlm.nih.gov/genome/11732?project_id=162357

**Comment by koadman** [comment]
This is simply because the most recent phylosift db update predated the public release of this genome to an accessible repository. It will be included during the next update cycle.
