### ISSUE TITLE
Propagate taxon names into jplace for markers generated with build_marker

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#307]
Markers generated with build_marker are not adding their gene IDs to the global gene_ids.aa.txt file, however this file is being consulted to name taxa in the jplace. The global gene_ids.aa.txt file should be obsoleted in favor of marker-local IDs.

**Comment by gjospin** [comment]
Fixed by having each marker have their own gene_id file when running through marker_build instead of 1 list for all markers.
