### ISSUE TITLE
holy guacamole batman warning for amplicon data

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#313]
When processing amplicon data, most sequences will hit a single or small set of markers. We should include a sanity check for this during the FastSearch stage, checking whether e.g. > 50% of sequences hit the same marker. If so we should warn the user that they really ought to run with a smaller chunk size, perhaps --chunk_size 10000 or so. And we should give 'em the bat signal.

```

       _==/          i     i          \==_
     /XX/            |\___/|            \XX\
   /XXXX\            |XXXXX|            /XXXX\
  |XXXXXX\_         _XXXXXXX_         _/XXXXXX|
 XXXXXXXXXXXxxxxxxxXXXXXXXXXXXxxxxxxxXXXXXXXXXXX
|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
 XXXXXX/^^^^"\XXXXXXXXXXXXXXXXXXXXX/^^^^^\XXXXXX
  |XXX|       \XXX/^^\XXXXX/^^\XXX/       |XXX|
    \XX\       \X/    \XXX/    \X/       /XX/
       "\       "      \X/      "      /"
```

**Comment by gjospin** [comment]
This will get triggered when

The total number of hits is > 10% of all the sequences processed in 1 chunk
AND 
The number of hits to 1 marker is greater than half of all the total number of hits
AND 
if the user has NOT manuall set a chunk_size (through phylosiftrc) aka using default values.
