### ISSUE TITLE
After latest code updates, --help screens now missing file input information

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#321]
Sparse usage information in the new hierarchical --help menu for PhyloSift - might be confusing for users.

Users will need to have file input information for each of the different modes. This is currently on the website but should also be accessible when running the code.

Need to reinstate example commands from previous versions of the phylosift.pl help screen.

**Comment by koadman** [comment]
Reinstated the original help text in commit 7e8df87.
