### ISSUE TITLE
pplacer error - related to concat.updated.gene_map file?

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#322]
Getting an error on yesterday's build of PhyloSift devel branch.  Ran command on my iMac (but this input data is also on Edhar):

./phylosift.pl all ~/Desktop/PhyloSift/test_data/xeno_unassembled/xeno_raw_s_2_1_sequence.txt --debug

I built the xeno marker packages (but missing the taxon map), and tried runnning PhloSift to see if I was getting hits to the new markers. However, I got this error: 

Removed 235 sequences on long pendant edges
Using markermap /Users/hollybik/share/phylosift/markers/concat.updated/concat.taxonmap
Reading taxonmap
Unable to read from /Users/hollybik/share/phylosift/markers/concat.updated/concat.updated.gene_map at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Utilities.pm line 85
        Phylosift::Utilities::ps_open('/Users/hollybik/share/phylosift/markers/concat.updated/concat...') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 504
        Phylosift::pplacer::read_name_map('marker', 'concat') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 522
        Phylosift::pplacer::name_taxa_in_jplace('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'input', '/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/PS...', 'output', '/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/PS...', 'taxonmap', 'HASH(0x7fc12154ee08)', 'marker', ...) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 366
        Phylosift::pplacer::place_reads('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker', 'concat', 'dna', 0, 'chunk', 1, 'reads', ...) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 80
        Phylosift::pplacer::pplacer('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker_reference', 'ARRAY(0x7fc121487a40)', 'chunk', 1) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/MarkerAlign.pm line 121
        Phylosift::MarkerAlign::MarkerAlign('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker_reference', 'ARRAY(0x7fc12135b358)', 'chunk', 1) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/FastSearch.pm line 141
        Phylosift::FastSearch::run_search('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker_reference', 'ARRAY(0x7fc12135b358)') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Phylosift.pm line 494
        Phylosift::Phylosift::run_search('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'cont', 0, 'marker', 'ARRAY(0x7fc12135b358)') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Phylosift.pm line 188
        Phylosift::Phylosift::run('Phylosift::Phylosift=HASH(0x7fc121662f48)', 'force', undef, 'custom', undef, 'cont', undef) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Command/all.pm line 103
        Phylosift::Command::all::execute('Phylosift::Command::all=HASH(0x7fc121685128)', 'Getopt::Long::Descriptive::Opts::**OPT**::2=HASH(0x7fc12168fa70)', 'ARRAY(0x7fc12114bcf0)') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/App/Cmd.pm line 243
        App::Cmd::execute_command('Phylosift=HASH(0x7fc1211a3cc0)', 'Phylosift::Command::all=HASH(0x7fc121685128)', 'Getopt::Long::Descriptive::Opts::**OPT**::2=HASH(0x7fc12168fa70)', '/Users/hollybik/Desktop/PhyloSift/test_data/xeno_unassembled/...') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/App/Cmd.pm line 171
        App::Cmd::run('Phylosift') called at ./bin/phylosift line 8

**Comment by gjospin** [comment]
What markers DB was used ? 
Devel markers have the .gene_map file required for this part of the code.  
Maybe it hadn't been updated at the time of the run.

**Comment by hollybik** [comment]
Re-downloaded newest version of phylosift and devel markers, and running xeno data now (after reindexing marker DB with xeno 18S marker added in). Will see if the error still pops up.

**Comment by koadman** [comment]
@hollybik Can we close this? I am not seeing similar errors on devel.

**Comment by hollybik** [comment]
This might be a mac specific issue? or perhaps an issue with my xeno marker package? On October 9th's version of devel I was getting another error (below). I will re-download last night's devel build to see if I can still replicate this.

Running /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../osx/pplacer --groups 15 --mmap-file abracadabra  -o /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/PS_temp/xeno_raw_s_2_1_sequence.txt/treeDir/concat.updated.1.jplace --verbosity 0 -j 1 -c /Users/hollybik/share/phylosift/markers/concat.updated "/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/PS_temp/xeno_raw_s_2_1_sequence.txt/alignDir/concat.updated.1.fasta"
Removed 235 sequences on long pendant edges
Using markermap /Users/hollybik/share/phylosift/markers/concat.updated/concat.taxonmap
Reading taxonmap
Unable to read from /Users/hollybik/share/phylosift/markers/concat.updated/concat.updated.gene_map at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Utilities.pm line 85
        Phylosift::Utilities::ps_open('/Users/hollybik/share/phylosift/markers/concat.updated/concat...') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 504
        Phylosift::pplacer::read_name_map('marker', 'concat') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 522
        Phylosift::pplacer::name_taxa_in_jplace('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'input', '/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/PS...', 'output', '/Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/PS...', 'taxonmap', 'HASH(0x7fc12154ee08)', 'marker', ...) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 366
        Phylosift::pplacer::place_reads('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker', 'concat', 'dna', 0, 'chunk', 1, 'reads', ...) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/pplacer.pm line 80
        Phylosift::pplacer::pplacer('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker_reference', 'ARRAY(0x7fc121487a40)', 'chunk', 1) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/MarkerAlign.pm line 121
        Phylosift::MarkerAlign::MarkerAlign('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker_reference', 'ARRAY(0x7fc12135b358)', 'chunk', 1) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/FastSearch.pm line 141
        Phylosift::FastSearch::run_search('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'marker_reference', 'ARRAY(0x7fc12135b358)') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Phylosift.pm line 494
        Phylosift::Phylosift::run_search('self', 'Phylosift::Phylosift=HASH(0x7fc121662f48)', 'cont', 0, 'marker', 'ARRAY(0x7fc12135b358)') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Phylosift.pm line 188
        Phylosift::Phylosift::run('Phylosift::Phylosift=HASH(0x7fc121662f48)', 'force', undef, 'custom', undef, 'cont', undef) called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/Phylosift/Command/all.pm line 103
        Phylosift::Command::all::execute('Phylosift::Command::all=HASH(0x7fc121685128)', 'Getopt::Long::Descriptive::Opts::**OPT**::2=HASH(0x7fc12168fa70)', 'ARRAY(0x7fc12114bcf0)') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/App/Cmd.pm line 243
        App::Cmd::execute_command('Phylosift=HASH(0x7fc1211a3cc0)', 'Phylosift::Command::all=HASH(0x7fc121685128)', 'Getopt::Long::Descriptive::Opts::**OPT**::2=HASH(0x7fc12168fa70)', '/Users/hollybik/Desktop/PhyloSift/test_data/xeno_unassembled/...') called at /Users/hollybik/Desktop/PhyloSift/phylosift_devel_20121009/bin/../lib/App/Cmd.pm line 171
        App::Cmd::run('Phylosift') called at ./bin/phylosift line 8

**Comment by gjospin** [comment]
I think this went away in Friday's tests.
