### ISSUE TITLE
Need a way to rename outputs after running only search & align

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#324]
During the database update `phylosift search` and `phylosift align` are run on all reference genomes. When these two steps are completed, sequence names in output files are currently still numbered. In order for the database update to proceed properly, we need to be able to swap the original sequence names back in. This could take the form of a very simple command front-end, e.g. something like `phylosift name my_run_directory`.

**Comment by gjospin** [comment]
Done.

usage : >./phylosift.pl name filename (filename2)
