### ISSUE TITLE
sequence coordinates in sequence_taxa.txt break benchmark

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#325]
The sequence_taxa.txt file now contains sequence coordinates appended to the sequence name. This is breaking our benchmark, which expects that column to contain only the sequence name. Probably we should move the coordinates into a separate column (I propose the 6th, right before marker names) and update documentation accordingly.

**Comment by gjospin** [comment]
Split the <seqname>.<coordinate> into 2 separate columns.
Modified summarize.pm and benchmark.pm to accomodate for that change.
Pushed to 121011_bowtie2_removal.
