### ISSUE TITLE
Smarter use of pplacer --mmap-file and --groups

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#339]
Right now --mmap-file and --groups are always used for the concat markers. However, on machines with sufficient memory pplacer might run much more quickly if --mmap-file were not used. We could check the available system RAM and only use --mmap-file if it was found to be insufficient.

**Comment by koadman** [comment]
This is related to issue #342.

**Comment by gjospin** [comment]
Leaving --groups alone for now. The major slowdown issue comes from --mmap-file.
Only adding --mmap-file when the machine has less than 8Gb of ram.

**Comment by gjospin** [comment]
Fixed in commit 50d3221f6c9befb0b9c02be9335047a8c82b29dc
