### ISSUE TITLE
Include all protein families as another amphora2 database

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#34]
The set of 350k protein families needs FastTrees with logs and pplacer reference packages created for them. These should go into a separate marker database since it's likely to be huge and not everybody will want it.

**Comment by hollybik** [comment]
Doesn't need to go through the taxonomic summery - we just need to get reads placed

**Comment by koadman** [comment]
Done on branch 120226_extended_markers. However, marker dataset is way too big and needs some tightening up for download such as removal of the .stk file and regeneration after download, possibly also for the HMM.
