### ISSUE TITLE
summarize's renaming breaks on finished run

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#340]
Redoing the summarize step when a run has previously finished (undergone the renaming of sequences) breaks the renaming of the sequence IDs.

Lots of error messages printed to the screen.  (Use of uninitialized value within %name_mapping)

**Comment by koadman** [comment]
I propose a solution of deleting the ID lookup table after renaming has occurred successfully.

**Comment by gjospin** [comment]
Fixed and implemented the suggestion.
