### ISSUE TITLE
16S rRNA data not being carried through to tree placement and taxonomy summary

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#359]
When I input 16S sequences I'm getting hits to 16S markers in the alignDir, but these sequences aren't being carried through to tree placement (treeDir is empty) or taxonomy summaries (all output files are empty)

Run is on Edhar: /home/hollybik/phylosift_devel_20121030/PS_temp/16S_NemMicrobiome_Aset_OCTUPUS_noChimeras_99

Command I ran: 
./phylosift.pl all --debug --marker_url="http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/devel" ~/TestData/OTU_data/16S_NemMicrobiome_Aset_OCTUPUS_noChimeras_99 

The run finished but I did see this message in the debug log (though this might have been because I had no jplace files): 

Naming taxa in marker 16s_reps_bac
Uncaught exception: Failure("Reference trees for 16s_reps_bac.long.1 and 16s_reps_bac.short.1 not the same! Were these run with the same reference tree and model parameters (e.g. statistics files?)")
Fatal error: exception Failure("Reference trees for 16s_reps_bac.long.1 and 16s_reps_bac.short.1 not the same! Were these run with the same reference tree and model parameters (e.g. statistics files?)")

**Comment by gjospin** [comment]
I just ran the same file on Noisy using
<code>./phylosift.pl all -f --debug sample_seq/16S_NemMicrobiome_Aset_OCTUPUS_noChimeras_99 </code>
I get alignments for 
16S long (428 seqs)
16S short (1481 seqs)
18S long (6 seqs)
18S short (57 seqs).

The 16S placement happened with no problem.
18S placement did not happen 
<code>Naming taxa in marker 18s_reps
Uncaught exception: Failure("Reference trees for 18s_reps.long.1 and 18s_reps.short.1 not the same! Were these run with the same reference tree and model parameters (e.g. statistics files?)")
Fatal error: exception Failure("Reference trees for 18s_reps.long.1 and 18s_reps.short.1 not the same! Were these run with the same reference tree and model parameters (e.g. statistics files?)")</code>

I have normal summary files generated only form the 16S jplace

**Comment by gjospin** [comment]
This should be fixed with the most recent markerDB distribution
