### ISSUE TITLE
Concurrent phylosift runs need to lock database before indexing 

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#360]
Currently when running multiple phylosift instances there is no way to prevent them all attempting to update/index the database at once. Need to have a read lock and write lock to support concurrency. We can do this with flock() in perl, as described here:
http://www.perlmonks.org/?node_id=7058

**Comment by gjospin** [comment]
Fixed using NSFLock to allow locking over the network.
flock works great as long as you don't have to go through a network.
Fixed in ed54786ec24778a0c6cd1b79f6e9a7ed05dd411c
