### ISSUE TITLE
Marker summary output on devel branch is looking funky

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#370]

**Comment by koadman** [comment]
??? can we please have some more details? funky like the chicken dance? or like your father's disco outfit?

**Comment by gjospin** [comment]
The parsing appears to be broken and some probabilities are showing up as
markers.

**Comment by hollybik** [comment]
funky like the open container of yogurt you left out on the counter for a week

**Comment by gjospin** [comment]
Funky indeed.  The sequence_taxa files parsing was updated to reflect the addition of the coordinates column however subsequent loops to capture the marker list were not.

I will push a fix soon.

**Comment by gjospin** [comment]
Fixed in commit 9a49bc2edf7c750e41f3e8638e0d25da6c6b053f

**Comment by gjospin** [comment]
I guess, it hasn't been fixed, I will need to investigate more.

**Comment by gjospin** [comment]
Unknown assignments are being printed with 2 probabilities.  Is that intended?

<code>$unclassifiable->{qname} / $placecount</code>
AND
<code>$unclassifiable->{$qname}

**Comment by gjospin** [comment]
Fixed in commit 2e7d808f3349a06a55bd4343d2735f5b80080a5d

**Comment by koadman** [comment]
Did you know you can close directly from your commit message? Just put something like Closes #370 in the message and not only will it close but the commit hashtag will be linked!
