### ISSUE TITLE
--extended doesn't produce any output

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#375]
The lastal DB gets generated using the following reference sequence headers:

1066/10669__641006681

This may be incorrectly interpreted when parsing lastal results.

Option 1:  Fix the parsing in FastSearch.pm
Option 2: Change the way sequences are being indexed as.

**Comment by koadman** [comment]
I vote for option 2. The only reason I can think of for keeping the prefix directory (option 1) is if we want to permit multiple markers with the same name in different directories. But there would be a LOT of other code that would need to change to support that, and it doesn't seem useful at all.

**Comment by gjospin** [comment]
Neither options were picked, the problem stemmed from a lingering $Phylosift::Utilities variable (should be $Phylosift::Settings) .

Fixed in b5a3eeabfb6b125049a9dc8f68e4725f99caa47d
