### ISSUE TITLE
Compare Dongying's euk marker genes with Parfrey phylogeny

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#38]

**Comment by koadman** [comment]
little overlap between Dongying's set and Parfey set based on gene names.  sequence identity comparison not done yet.

**Comment by hollybik** [comment]
BLASTed all of the Parfrey euk markers against Dongying's data. Based on BLAST similarity, we have FOUR prospective 3-domain markers, as follows:

Euk Ef2 - Similarity to bac/arc Ef2 (PMPROK00060)
Euk grc5 - Similarity to bac/arc L16/L10E (PMPROK00071)
Euk rps22 - similarity to bac/arc Ribosomal Protein S8P (PMPROK00074)
Euk Rps23a - similarity to bac/arch Ribosomal Protein S12P (PMPROK00094)

Next step should be to compare the HMMs for these markers and think about merging these into one alignment if the profile alignments seem to match well.

**Comment by koadman** [comment]
I scanned S. cerevisiae against our markers (trying to test new euk markers) and found that 33 of Dongying's PMPROK markers had near full-length homologs. Is there some way we can reconcile this observation with your findings? I just used phylosift itself to do the search, including any frameshift/exon splicing that may have been done from the genomic DNA.

**Comment by koadman** [comment]
@hollybik wrote:

"Its possible that yeast gets hits to Dongying's markers, but the specific Parfrey euk marker genes specifically don't seem to be homologs with the bacterial/archaeal PMPROK (except in 4 cases). So based on Aaron's results Dongying's markers might be more taxonomically broad than we initially thought (and the Parfrey markers might be more eukaryote-specific)."

This makes sense to me.
