### ISSUE TITLE
Error in Summarize.pm when running non-paired end data

### ISSUE THREAD

**Issue by mayalowe** [gjospin/PhyloSift#383]
Running phylosift all on the simulated dataset I use for benchmarking; here's an excerpt of the error:

Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 1.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 9.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 15.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 3.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 7.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 11.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 15.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 17.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 23.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 27.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 31.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 33.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 37.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 45.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 47.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 51.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 55.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 57.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 59.
Use of uninitialized value within %name_mapping in concatenation (.) or string at /home/elowe/PhyloSift/bin
/../lib/Phylosift/Summarize.pm line 820, <$FH> line 63.

**Comment by gjospin** [comment]
Where can we find the data set ?

**Comment by mayalowe** [comment]
Ahh yes, sorry about that.  

Edhar:~elowe/sim_data1/knockoutexp_ill_fastq-reads.fastq

**Comment by koadman** [comment]
I saw this same error on the grinder_illumina dataset used by the benchmark server. The code seemed to continue past it to produce meaningful results, but it's an awfully ugly set of messages.

**Comment by gjospin** [comment]
This is happening when renaming on (in alignDir)
.unmasked and codon.updated._.fasta but not on .updated._.fasta or
newCandidate.aa files.

Results should be fine. And all other files seem to not have that problem
when renaming.

**Comment by gjospin** [comment]
So, this is just speculation but maybe we have a slightly different format for writing out the two files previously mentioned so the regex used to convert from unique IDs to original IDs does not work.
I will try to get around to it this afternoon if no one has done so by then
