### ISSUE TITLE
Phylosift Marker - Missing Taxon Maps 2176/217691, 2781/278137, 2683/268328

### ISSUE THREAD

**Issue by DBiteng** [gjospin/PhyloSift#401]
Hi. I am running phylosift against my data and have the following taxon maps missing. How do I fix this? Please help! Thanks much.

 2176/217691, 2781/278137, 2683/268328

**Comment by gjospin** [comment]
It looks like you are running using the --extended flag.  The extended
database is still a work in progress. We are working to clear out some of
the bugs from the downloadable extended markers.
This is a known issue however it will not affect the validity of the
results, those problematic markers will not be taken into consideration
when compiling the summary files at the end of the pipeline.

**Comment by DBiteng** [comment]
Hi. Unfortunately, I couldn't get any hits out of the --updated marker option. Is there something I am missing? Thanks.

**Comment by gjospin** [comment]
Can you post the command you are using as well as error messages that show
up please?
--updated is an old option that may not be necessary with the current state
of the code.

A standard command would look like:

> ./phylosift all <filename>
> or
> ./phylosift all --paired <filename1> <filename2>

**Comment by DBiteng** [comment]
Hi. This is the command I am using:

./phylosift all -f --debug --updated <sequence file>

The inputs are samples from: http://trace.ddbj.nig.ac.jp/DRASearch/study?acc=SRP003167

Will post runtime msgs in awhile. Still waiting for a job to finish. Thanks!

**Comment by koadman** [comment]
@gjospin can you confirm if the new markers (which are now live) allow us to close this issue?

**Comment by gjospin** [comment]
This is related to extended markers which I think are the same as before. However the code changed to not display such errors. They were annoying but not critical to the good progress of ps.
