### ISSUE TITLE
PhyloSift run info text obscuring read placement info in Krona report

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#402]
PhyloSift run information printed into the Krona report is currently obscuring the information about reads placed in the upper right hand corner (see screenshot below from run that finished on our v1.0.0 beta release). This is particularly bad when viewing the "all markers" Krona.

![Screen Shot 2012-12-11 at 10 14 46 AM](https://f.cloud.github.com/assets/1392119/6415/f1c8e68c-43be-11e2-98d5-b96656e4c777.png)

**Comment by gjospin** [comment]
Should be fixed with b0b4232754532532cf63f8c7ea7b007928cadccf
Also moved the link to view phylogenetic placements at the bottom of the page where it is less likely to be interfering with the krona buttons.
