### ISSUE TITLE
taxon not found in alignment ?

### ISSUE THREAD

**Issue by ewilbanks** [gjospin/PhyloSift#404]
Hey Phylosifters,

I'm getting the following error trying to run phylosift (on our edhar server).  It's currently just sitting there (top says its running perl) - I'm guessing it's stuck?    Any thoughts?

--Lizzy
......
Found newer version of the marker data
Downloading from http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift_markers/markers.tgz
Inside index_marker_db
Found newer version of NCBI taxonomy data!
Downloading from http://edhar.genomecenter.ucdavis.edu/~koadman/ncbi.tgz
query 108.1.5691.6374 is not the same length as the reference alignment (got 16524; expected 8460)
Uncaught exception: Failure("taxon not found in alignment: '323595'")
Fatal error: exception Failure("taxon not found in alignment: '323595'")
Use of uninitialized value $place_file in -e at /home/ewilbanks/phylosift_v1.0.0_01/bin/../lib/Phylosift/pplacer.pm line 102.

**Comment by gjospin** [comment]
You are not stuck. The pipeline is still going just processing some other
information.
This marker would end up not showing up in the end summaries as it was not
fully processed.
We need to know what marker this is coming from. It could come from a
marker that hasn't been run through a recent update.  We could tell by
getting some output when using the --debug flag when running PS.

Thanks for the feedback.
