### ISSUE TITLE
Establish web presence/Twitter feed

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#41]

**Comment by koadman** [comment]
holdup on this has been the name game. solved that and sounds like twitter happened...

**Comment by matsen** [comment]
sooooo....?

**Comment by hollybik** [comment]
Pleased to announce... PhyloSift

On twitter: https://twitter.com/#!/phylosift
And on the blog: http://phylosift.wordpress.com/

Official logo is pending, but release is imminent.

**Comment by hollybik** [comment]
Web presence officially established, now all we need to do is add content!!
