### ISSUE TITLE
Installing Phylosift

### ISSUE THREAD

**Issue by sbranco** [gjospin/PhyloSift#410]
Hi,

I'm having problems installing Phylosift - am sending the error below. Any suggestions? 

Thanks!

Sara

[sbranco@vector phylosift_v1.0.0_01]$ bin/phylosift -h
Can't locate version.pm in @INC (@INC contains: /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 . /global/home/users/sbranco/download/phylosift_v1.0.0_01/bin/../lib) at /global/home/users/sbranco/download/phylosift_v1.0.0_01/bin/../lib/Phylosift/Command.pm line 6.
BEGIN failed--compilation aborted at /global/home/users/sbranco/download/phylosift_v1.0.0_01/bin/../lib/Phylosift/Command.pm line 6.
Compilation failed in require at /global/home/users/sbranco/download/phylosift_v1.0.0_01/bin/../lib/Phylosift.pm line 2
BEGIN failed--compilation aborted at /global/home/users/sbranco/download/phylosift_v1.0.0_01/bin/../lib/Phylosift.pm line 2.
Compilation failed in require at bin/phylosift line 7.
BEGIN failed--compilation aborted at bin/phylosift line 7.

**Comment by gjospin** [comment]
Hello,
It doesn't look like we are distributing the version.pm perl module with PhyloSift.
I would recommend installing version.pm directly and adding its location to your $PERL5LIB variable.  Or if you can install it globally on your machine it might be easier than modifying the $PERL5LIB variable.
Here is the cpan page for the module you are looking for. 
http://search.cpan.org/~jpeacock/version-0.9902/lib/version.pod

I hope this helps.
Let us know if you have more problems.

Cheers.

**Comment by Mikeyj** [comment]
Hey - I'm having an install problem too - though a different issue I think.  After unzipping and attempting to run the suggested first command I get:

``` S
Could not find a suitable Class::Load implementation: Can't locate loadable object for module Class::Load::XS in @INC (@INC contains: /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib64/perl5/site_perl/5.8.7/x86_64-linux-thread-multi /usr/lib64/perl5/site_perl/5.8.6/x86_64-linux-thread-multi /usr/lib64/perl5/site_perl/5.8.5/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl/5.8.7 /usr/lib/perl5/site_perl/5.8.6 /usr/lib/perl5/site_perl/5.8.5 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib64/perl5/vendor_perl/5.8.7/x86_64-linux-thread-multi /usr/lib64/perl5/vendor_perl/5.8.6/x86_64-linux-thread-multi /usr/lib64/perl5/vendor_perl/5.8.5/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl/5.8.7 /usr/lib/perl5/vendor_perl/5.8.6 /usr/lib/perl5/vendor_perl/5.8.5 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 . /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib) at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Module/Runtime.pm line 313
Compilation failed in require at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Module/Runtime.pm line 313.
Could not find a suitable Package::Stash implementation: Can't locate Package/Stash/XS.pm in @INC (@INC contains: /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib64/perl5/site_perl/5.8.7/x86_64-linux-thread-multi /usr/lib64/perl5/site_perl/5.8.6/x86_64-linux-thread-multi /usr/lib64/perl5/site_perl/5.8.5/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl/5.8.7 /usr/lib/perl5/site_perl/5.8.6 /usr/lib/perl5/site_perl/5.8.5 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib64/perl5/vendor_perl/5.8.7/x86_64-linux-thread-multi /usr/lib64/perl5/vendor_perl/5.8.6/x86_64-linux-thread-multi /usr/lib64/perl5/vendor_perl/5.8.5/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl/5.8.7 /usr/lib/perl5/vendor_perl/5.8.6 /usr/lib/perl5/vendor_perl/5.8.5 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 . /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib) at (eval 39) line 1.
Weak references are not implemented in the version of perl at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Package/Stash/PP.pm line 11
BEGIN failed--compilation aborted at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Package/Stash/PP.pm line 11.
Compilation failed in require at (eval 40) line 1.
 at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Package/Stash.pm line 46
BEGIN failed--compilation aborted at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Package/Stash.pm line 46.
Compilation failed in require at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Class/Load/PP.pm line 9.
BEGIN failed--compilation aborted at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Class/Load/PP.pm line 9.
Compilation failed in require at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Module/Runtime.pm line 313.
 at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Class/Load.pm line 24
Compilation failed in require at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/App/Cmd.pm line 15.
BEGIN failed--compilation aborted at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/App/Cmd.pm line 15.
Compilation failed in require at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/App/Cmd/Setup.pm line 10.
BEGIN failed--compilation aborted at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/App/Cmd/Setup.pm line 10.
Compilation failed in require at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Phylosift.pm line 2.
BEGIN failed--compilation aborted at /mnt/ris-fas1a/ark1/software/phylosift_v1.0.0_01/bin/../lib/Phylosift.pm line 2.
Compilation failed in require at ../../../software/phylosift_v1.0.0_01/bin/phylosift line 7.
BEGIN failed--compilation aborted at ../../../software/phylosift_v1.0.0_01/bin/phylosift line 7.
```

Looks like perl not set up quite right for this, does it look like missing modules again? Thought it might be a perl version problem given the mention of weak references not being implemented?

Cheers

Mike

**Comment by koadman** [comment]
Yes looks like a missing perl module, Class::Load. The quickest fix
might be to install it via CPAN. I notice that the version of perl on
your system is 5.8.8, which we have been using successfully on CentOS
linux.

**Comment by koadman** [comment]
These dependencies should either be included in the next phylosift release or documented as required to be manually installed on systems that have older perl installations

**Comment by koadman** [comment]
This should be fixed now on the devel branch.
