### ISSUE TITLE
Reading zipped file not working on Macs

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#413]
Apparently it is adding a .Z at the end of the file names when trying to read zipped files on a Mac.

**Comment by gjospin** [comment]
Can't reproduce the error on my Davis Mac. 
Will check on a computer that showed such error.

**Comment by gjospin** [comment]
Found this website that explains a work around.
http://od-eon.com/blogs/calvin/zcat-bug-mac-osx/

**Comment by koadman** [comment]
Fixed directly in phylosift via commit 039dac9
solution was to replace `zcat` with `gzip -dc`
