### ISSUE TITLE
incorporate new versions of pplacer and guppy

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#424]
Erick Matsen says that the posterior probability calculations have been sped up substantially in newer pplacer versions. This is great news since the p.p. calc is one of the slowest parts of a phylosift run right now. Need to incorporate the new pplacer release.

**Comment by koadman** [comment]
Need help from @matsen on this one. The pplacer builds on the pplacer web site target linux kernel 2.6.24 and os x 10.7+, whereas the rest of our tools work with 2.6.15+ and os x 10.5+. Attempts to rebuild on OS X 10.5 are failing...

**Comment by matsen** [comment]
We don't have access to a machine that has OS X 10.5. If you can supply
access we should be able to set up a buildbot on it.

On Mon, Jul 22, 2013 at 11:05 PM, Aaron Darling notifications@github.comwrote:

> Need help from @matsen https://github.com/matsen on this one. The
> pplacer builds on the pplacer web site target linux kernel 2.6.24 and os x
> 10.7+, whereas the rest of our tools work with 2.6.15+ and os x 10.5+.
> Attempts to rebuild on OS X 10.5 are failing...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gjospin/PhyloSift/issues/424#issuecomment-21394924
> .

## 

Frederick "Erick" Matsen, Assistant Member
Fred Hutchinson Cancer Research Center
http://matsen.fhcrc.org/

**Comment by koadman** [comment]
thank you @matsen ! 
will be in touch with an IP & login creds.
is the linux 2.6.15 bit do-able?
UCD's cluster compute system is on 2.6.18 and I assume there are many
other compute clusters out there that get updated all-too-infrequently.

**Comment by matsen** [comment]
Well, could we build on your linux server too? Folks around here are rabid
about updating.

On Tue, Jul 23, 2013 at 5:06 PM, Aaron Darling notifications@github.comwrote:

> thank you @matsen !
> will be in touch with an IP & login creds.
> is the linux 2.6.15 bit do-able?
> UCD's cluster compute system is on 2.6.18 and I assume there are many
> other compute clusters out there that get updated all-too-infrequently.
> 
> On Tue, 2013-07-23 at 15:02 -0700, Erick Matsen wrote:
> 
> > We don't have access to a machine that has OS X 10.5. If you can
> > supply
> > access we should be able to set up a buildbot on it.
> > 
> > On Mon, Jul 22, 2013 at 11:05 PM, Aaron Darling
> > notifications@github.comwrote:
> > 
> > > Need help from @matsen https://github.com/matsen on this one. The
> > > pplacer builds on the pplacer web site target linux kernel 2.6.24
> > > and os x
> > > 10.7+, whereas the rest of our tools work with 2.6.15+ and os x 10.5
> > > +.
> > > Attempts to rebuild on OS X 10.5 are failing...
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/gjospin/PhyloSift/issues/424#issuecomment-21394924>
> > > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gjospin/PhyloSift/issues/424#issuecomment-21455429
> .

## 

Frederick "Erick" Matsen, Assistant Member
Fred Hutchinson Cancer Research Center
http://matsen.fhcrc.org/

**Comment by koadman** [comment]
my os x 10.5 build mac is locked in an office in Davis, I don't have the IP, and the person with the key is out all week!

For linux, I can set up a build VM and send login creds but don't have admin privs to hand out access to UC Davis' (ancient) CentOS 5.3 cluster machines.

**Comment by koadman** [comment]
Done & dusted.
