### ISSUE TITLE
--paired requires correctly paired read

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#429]
Need to document the requirement on having correctly paired reads without orphans when using the --paired flag.
Interleaved files are acceptable. 
I didn't find much about the actual workings/requirements of --paired on the website but we might need to adjust things there in addition to the readme/command help

I don't think the following is appropriate anymore:

--paired             Looks for 2 input files (paired end sequencing)
                         in FastQ format. Reversing the sequences for the
                         second file listed and appending to the
                         corresponding pair from the first file listed.

**Comment by koadman** [comment]
@hollybik the help message in the code is now updated, would you mind adding a note somewhere on the web site docs so we can close this?

**Comment by hollybik** [comment]
Updated on website: http://phylosift.wordpress.com/tutorials/running-phylosift/phylosift-overview/

Changed the --paired description to reflect the command line documentation, and updated the info about interleaved file formats to warn against orphan/unpaired reads.
