### ISSUE TITLE
LWP error

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#434]
The addition of the LWP require inside of Utilities is causing an warning to show up on both Noisy and Merlot tests.

Unable to load LWP::Simple, unable to check for updates to or download the NCBI taxonomy. at /home/gjospin/git/PhyloSift/lib/Phylosift/Utilities.pm line 610.

**Comment by koadman** [comment]
Fixed by eliminating LWP from included modules, only checking for updates if LWP is already present on the system.
