### ISSUE TITLE
Need to detect input type from previous runs

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#441]
Currently testing running the search and align steps one after the other on the paired HMP tutorial data.
<code>
./phylosift search --paired --debug tutorial_data/HMP_1.fastq.gz tutorial_data/HMP_2.fastq.gz
./phylosift align --paired --debug tutorial_data/HMP_1.fastq.gz tutorial_data/HMP_2.fastq.gz
</code>
In the search workflow, the data type gets flagged as DNA 
In the align workflow, the data type defaults to Protein as the data type detection happens in the search step.  This prevents the generation of the codon files (here V367.codon.updated.1.fasta) and breaks the read merger mechanics.

I can think of multiple options:
1 - Record the data type in the run_info.txt file. Since we are reading it to figure out what steps were completed, find the flag and store it for other steps in the workflow.
2 - Allow the user to force a data type on the command line.
3 - Add an error handling statement to skip parts of the workflow when the file does not exists.
4 - When --paired is used force the data type to be DNA.

Below is the error and debug statement.

TYPE : protein

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not open /home/gjospin/git/PhyloSift/PS_temp/HMP_1.fastq.gz/alignDir/V367.codon.updated.1.fasta: No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.14.2/Bio/Root/Root.pm:368
STACK: Bio::Root::IO::_initialize_io /usr/local/share/perl/5.14.2/Bio/Root/IO.pm:341
STACK: Bio::SeqIO::_initialize /usr/local/share/perl/5.14.2/Bio/SeqIO.pm:467
STACK: Bio::SeqIO::fasta::_initialize /usr/local/share/perl/5.14.2/Bio/SeqIO/fasta.pm:94
STACK: Bio::SeqIO::new /usr/local/share/perl/5.14.2/Bio/SeqIO.pm:360
STACK: Bio::SeqIO::new /usr/local/share/perl/5.14.2/Bio/SeqIO.pm:390
STACK: Phylosift::Utilities::open_SeqIO_object /home/gjospin/git/PhyloSift/lib/Phylosift/Utilities.pm:1813
STACK: Phylosift::MarkerAlign::merge_alignment /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:613
STACK: Phylosift::MarkerAlign::alignAndMask /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:593
STACK: Phylosift::MarkerAlign::MarkerAlign /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:81
STACK: Phylosift::Phylosift::run_marker_align /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:401
STACK: Phylosift::Phylosift::run_later_stages /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:197
STACK: Phylosift::Phylosift::run /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:180
STACK: Phylosift::Command::align::execute /home/gjospin/git/PhyloSift/lib/Phylosift/Command/align.pm:53
STACK: App::Cmd::execute_command /home/gjospin/git/PhyloSift/lib/App/Cmd.pm:243
STACK: App::Cmd::run /home/gjospin/git/PhyloSift/lib/App/Cmd.pm:171

**Comment by koadman** [comment]
What about doing a detection only if the seq type is unknown at the start of each step? Carrying around more info in run_info.txt feels icky somehow

Guillaume Jospin notifications@github.com wrote:

> Currently testing running the search and align steps one after the
> other on the paired HMP tutorial data.
> <code>
> ./phylosift search --paired --debug tutorial_data/HMP_1.fastq.gz
> tutorial_data/HMP_2.fastq.gz
> ./phylosift align --paired --debug tutorial_data/HMP_1.fastq.gz
> tutorial_data/HMP_2.fastq.gz
> </code>
> In the search workflow, the data type gets flagged as DNA 
> In the align workflow, the data type defaults to Protein as the data
> type detection happens in the search step.  This prevents the
> generation of the codon files (here V367.codon.updated.1.fasta) and
> breaks the read merger mechanics.
> 
> I can think of multiple options:
> 1 - Record the data type in the run_info.txt file. Since we are reading
> it to figure out what steps were completed, find the flag and store it
> for other steps in the workflow.
> 2 - Allow the user to force a data type on the command line.
> 3 - Add an error handling statement to skip parts of the workflow when
> the file does not exists.
> 4 - When --paired is used force the data type to be DNA.
> 
> Below is the error and debug statement.
> 
> TYPE : protein
> 
> ------------- EXCEPTION: Bio::Root::Exception -------------
> MSG: Could not open
> /home/gjospin/git/PhyloSift/PS_temp/HMP_1.fastq.gz/alignDir/V367.codon.updated.1.fasta:
> No such file or directory
> STACK: Error::throw
> STACK: Bio::Root::Root::throw
> /usr/local/share/perl/5.14.2/Bio/Root/Root.pm:368
> STACK: Bio::Root::IO::_initialize_io
> /usr/local/share/perl/5.14.2/Bio/Root/IO.pm:341
> STACK: Bio::SeqIO::_initialize
> /usr/local/share/perl/5.14.2/Bio/SeqIO.pm:467
> STACK: Bio::SeqIO::fasta::_initialize
> /usr/local/share/perl/5.14.2/Bio/SeqIO/fasta.pm:94
> STACK: Bio::SeqIO::new /usr/local/share/perl/5.14.2/Bio/SeqIO.pm:360
> STACK: Bio::SeqIO::new /usr/local/share/perl/5.14.2/Bio/SeqIO.pm:390
> STACK: Phylosift::Utilities::open_SeqIO_object
> /home/gjospin/git/PhyloSift/lib/Phylosift/Utilities.pm:1813
> STACK: Phylosift::MarkerAlign::merge_alignment
> /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:613
> STACK: Phylosift::MarkerAlign::alignAndMask
> /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:593
> STACK: Phylosift::MarkerAlign::MarkerAlign
> /home/gjospin/git/PhyloSift/lib/Phylosift/MarkerAlign.pm:81
> STACK: Phylosift::Phylosift::run_marker_align
> /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:401
> STACK: Phylosift::Phylosift::run_later_stages
> /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:197
> STACK: Phylosift::Phylosift::run
> /home/gjospin/git/PhyloSift/lib/Phylosift/Phylosift.pm:180
> STACK: Phylosift::Command::align::execute
> /home/gjospin/git/PhyloSift/lib/Phylosift/Command/align.pm:53
> STACK: App::Cmd::execute_command
> /home/gjospin/git/PhyloSift/lib/App/Cmd.pm:243
> STACK: App::Cmd::run /home/gjospin/git/PhyloSift/lib/App/Cmd.pm:171
> 
> ## STACK: /home/gjospin/git/PhyloSift/bin/phylosift:8
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gjospin/PhyloSift/issues/441

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by gjospin** [comment]
Fixed in commit d003d04b4258a93840cd4e5e07817617b1956930

We were already checking the file type, the problem came from reading a zipped file without the gunzip utilities.
