### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by kgwin1** [gjospin/PhyloSift#444]
I get the following message after installing:
Can't locate App/Cmd/Setup.pm in @INC (@INC contains: /home/localuser/Desktop/PhyloSift/bin/../lib /home/localuser/Desktop/PhyloSift/version-0.9902/lib/ /home/localuser/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/x86_64-linux /home/localuser/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0 /home/localuser/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux /home/localuser/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0 .) at /home/localuser/Desktop/PhyloSift/bin/../lib/Phylosift.pm line 2.
BEGIN failed--compilation aborted at /home/localuser/Desktop/PhyloSift/bin/../lib/Phylosift.pm line 2.
Compilation failed in require at /home/localuser/Desktop/PhyloSift/bin/phylosift line 6.
BEGIN failed--compilation aborted at /home/localuser/Desktop/PhyloSift/bin/phylosift line 6.
Any suggestions? Thanks!

**Comment by koadman** [comment]
Hi kgwin1, what did you do to "install" phylosift? You should be able to run it without any kind of installation, just unpack the archive and run. Is that what you've done?

**Comment by kgwin1** [comment]
I ran git clone git://github.com/gjospin/PhyloSift.git

**Comment by kgwin1** [comment]
Nevermind, I have since deleted that and reinstalled via website and unzipped! Now it works.

**Comment by gjospin** [comment]
Excellent, I was about to suggest that.
Thanks for letting us know.

**Comment by kgwin1** [comment]
Just another quick question: running the whole workflow with the all command gives me this error:
rm: cannot remove `/home/localuser/Desktop/phylosift_v1.0.0_02/PS_temp/simulated_BEI20_0.01percent.fasta/blastDir/_.aa.1_': No such file or directory

Am I missing something?

**Comment by gjospin** [comment]
The files resulting from the search step get deleted automatically (unless
--debug is used  --keep_search I think).
It could be that you didn't get any hits and there were no files to remove.
It could also be that you have uncovered a bug that needs fixing.

Are you getting results such as a krona plot or anything in the alignDir or
treeDir directories?  If you are seeing results files, I wouldn't worry too
much about the message you reported as it's just trying to delete something
that is not there.  It would not be hurting the end results.

I am assuming you have downloaded the marker database and indexed it prior
to running the workflow.  No index would mean no search hits but there
would have been a nasty error if that happened.

**Comment by kgwin1** [comment]
No, I am not seeing anything in treeDir or alignDir. No I have not downloaded the marker database or indexed it. Was the 16S database not included?

**Comment by gjospin** [comment]
It should automatically download the marker DB when you start Phylosift.  I
would recommend running the following command just to make sure.

> ./phylosift index

**Comment by kgwin1** [comment]
Okay. I tried that and got the same error message. I'm inputting a fasta file and the program is straight forward. Am I missing something else? My command:
./phylosift all $HOME/simulated_data.fasta'

**Comment by gjospin** [comment]
Check $HOME/share/phylosift to make sure you have the database downloaded.
 You should have a markers directory (with about 850 markers) and a ncbi
directory with a few files related to taxonomy.

What system are you running PS on?
Could you provide an output dump when running your command using the
--debug flag.  This would help figure out what is going wrong.

**Comment by kgwin1** [comment]
Here is the output. Thanks again for all your help!

FORCE: 1
Continue : 
force : 1
PhyloSift -- Phylogenetic analysis of genomes and metagenomes
(c) 2011, 2012 Aaron Darling and Guillaume Jospin

CITATION:
        PhyloSift. A. E. Darling, G. Jospin, E. Lowe, F. A. Matsen, H. M. Bik, J. A. Eisen. Submitted to PeerJ

PhyloSift incorporates several other software packages, please consider also citing the following papers:

```
    pplacer: linear time maximum-likelihood and Bayesian phylogenetic placement of sequences onto a fixed reference tree.
    Frederick A Matsen, Robin B Kodner, and E Virginia Armbrust
    BMC Bioinformatics 2010, 11:538

    Adaptive seeds tame genomic sequence comparison.
    SM Kielbasa, R Wan, K Sato, P Horton, MC Frith
    Genome Research 2011.

    Infernal 1.0: Inference of RNA alignments
    E. P. Nawrocki, D. L. Kolbe, and S. R. Eddy
    Bioinformatics 25:1335-1337 (2009)

    Bowtie: Ultrafast and memory-efficient alignment of short DNA sequences to the human genome.
    Langmead B, Trapnell C, Pop M, Salzberg SL. Genome Biol 10:R25.

    HMMER 3.0 (March 2010); http://hmmer.org/
    Copyright (C) 2010 Howard Hughes Medical Institute.
    Freely distributed under the GNU General Public License (GPLv3).

    Phylogenetic Diversity within Seconds.
    Bui Quang Minh, Steffen Klaere and Arndt von Haeseler
    Syst Biol (2006) 55 (5): 769-773.
```

Before START 2013-12-06 08:27:24
All systems are good to go, continuing the screening
MODE : all
Using updated markers
Using a marker list file /home/localuser/share/phylosift/markers/marker_list.txt
Before runBlast 2013-12-06 08:27:24
USING 0
Input type is dna, fasta
Making fifos
Launching search process 1
Running /home/localuser/Desktop/phylosift_v1.0.0_02/bin/lastal -F15 -e75 -f0 /home/localuser/share/phylosift/markers/replast "/home/localuser/Desktop/phylosift_v1.0.0_02/PS_temp/simulated_BEI20_0.01percent.fasta/blastDir/last_0.pipe" |Opening /home/localuser/Desktop/phylosift_v1.0.0_02/PS_temp/simulated_BEI20_0.01percent.fasta/blastDir/reads.fasta.1
Octopus is handing out sequences
Octopus handed out 15200 sequences
Writing candidates from process 1
ReadsFile:  /home/localuser/Desktop/Qiime_supermike/simulated_data_100bp/simulated_BEI20_0.01percent.fasta
.lastal Got 0 markers with hits
.lastal Got 0 nucleotide markers with hits
After runBlast 2013-12-06 08:27:24
Before runAlign 2013-12-06 08:27:24
after marker prep
AFTER ALIGN and MASK
Using a marker list file /home/localuser/share/phylosift/markers/marker_list.txt
Using a marker list file /home/localuser/share/phylosift/markers/marker_list.txt
AFTER concatenateALI
After runAlign 2013-12-06 08:27:24
Before runPplacer 2013-12-06 08:27:24
After runPplacer 2013-12-06 08:27:24
Before runSummarize 2013-12-06 08:27:24

******STARTING SUMMARY 

Writing sequences
Total classifiable probability mass is 0
Before runKrona 2013-12-06 08:27:24
Generating krona
After runKrona 2013-12-06 08:27:24
Debug lvl : 1
After runBlast 2013-12-06 08:27:24
MODE :: all
After START 2013-12-06 08:27:24

**Comment by kgwin1** [comment]
I'm using a simulated dataset composed of 100b randomly chopped 16S sequences from 20 bacterial species to test the program and see what the outputs are.

**Comment by kgwin1** [comment]
This may be the issue, my marker_list.txt is blank. I'm not sure how that happened

**Comment by koadman** [comment]
Hi Kelley, that is definitely a problem. I'm not sure how it happened
but can suggest a course of action to resolve it. First delete the
marker_list.txt and then re-run `phylosift index --debug`. If that
doesn't solve the problem you can delete the entire marker directory,
which should trigger a re-download and index next time you run
PhyloSift. Hope that helps.
