### ISSUE TITLE
issue encountered during tutorial data run

### ISSUE THREAD

**Issue by sschmedes** [gjospin/PhyloSift#446]
I ran the tutorial data with PhyloSift and encountered this message 6 times near the end of the run.

Use of uninitialized value $taxon_level in join or string at /home/cbh250/phylosift/bin/../lib/Phylosift/Summarize.pm line 527

Is this a bug?

**Comment by gjospin** [comment]
This means that the $taxon_level string will be empty in the tree files.  A taxonID will be displayed instead of a name

**Comment by koadman** [comment]
Fixed by 4cec91c
