### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by lindaoyam** [gjospin/PhyloSift#452]
I downloaded Phylosift to try the software for the first time. It seems that one of the packages 'placer' isn't found even though I can see it in the 'bin' directory. Please what could be causing this error message? See screen below:

Linda Oyama@LindaOyama-PC /cygdrive/c/phylosift_20131016/bin
$ ./phylosift search yamasphylosiftexample.txt
PhyloSift -- Phylogenetic analysis of genomes and metagenomes
(c) 2011, 2012 Aaron Darling and Guillaume Jospin

CITATION:
                PhyloSift. A. E. Darling, G. Jospin, E. Lowe, F. A. Matsen, H. M. Bik, J. A. Eisen. Submitted to PeerJ

PhyloSift incorporates several other software packages, please consider also citing the following papers:

```
            pplacer: linear time maximum-likelihood and Bayesian phylogenetic placement of sequences onto a fixed reference tree.
            Frederick A Matsen, Robin B Kodner, and E Virginia Armbrust
            BMC Bioinformatics 2010, 11:538

            Adaptive seeds tame genomic sequence comparison.
            SM Kielbasa, R Wan, K Sato, P Horton, MC Frith
            Genome Research 2011.

            Infernal 1.0: Inference of RNA alignments
            E. P. Nawrocki, D. L. Kolbe, and S. R. Eddy
            Bioinformatics 25:1335-1337 (2009)

            Bowtie: Ultrafast and memory-efficient alignment of short DNA sequences to the human genome.
            Langmead B, Trapnell C, Pop M, Salzberg SL. Genome Biol 10:R25.

            HMMER 3.0 (March 2010); http://hmmer.org/
            Copyright (C) 2010 Howard Hughes Medical Institute.
            Freely distributed under the GNU General Public License (GPLv3).

            Phylogenetic Diversity within Seconds.
            Bui Quang Minh, Steffen Klaere and Arndt von Haeseler
            Syst Biol (2006) 55 (5): 769-773.
```

The system cannot find the path specified.
pplacer not found at C:/phylosift_20131016/bin/../lib/Phylosift/Phylosift.pm line 287.
A required program was not found during the checks aborting
 at C:/phylosift_20131016/bin/../lib/Phylosift/Command/search.pm line 54.

Linda Oyama@LindaOyama-PC /cygdrive/c/phylosift_20131016/bin
$

**Comment by koadman** [comment]
Hi Linda, phylosift will not work on windows PCs, not even when using cygwin. Consider setting up a Linux virtual machine using one of the many good VM software options, or find an existing Linux or Mac to use.
