### ISSUE TITLE
Document .codon.updated.sub1.1.fasta files

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#454]
The documentation needs a description of what these files are. It can be based on the following email exchange:
https://groups.google.com/forum/#!topic/phylosift/I33jalfKqW4

**Comment by hollybik** [comment]
Added new file description and explanation under AlignDir on the outputs page, including the discussion of rationale from the Google Group thread:
http://phylosift.wordpress.com/tutorials/phylosift-outputs/
