### ISSUE TITLE
Missing ribbon

### ISSUE THREAD

**Issue by ryneches** [gjospin/PhyloSift#455]
The PhyloSift website (http://phylosift.wordpress.com/) is missing a "Fork me on GitHub!" ribbon.

https://github.com/blog/273-github-ribbons

**Comment by hollybik** [comment]
These ribbons are ugly. Plus, we already have a clear link to our GitHub repo in the righthand sidebar on all pages.

**Comment by ryneches** [comment]
Well, "clear" is not how I would describe it. In graphic design terms,
it's "buried."

It's in tiny text, jumbled amongst marginally related information. I had
to ctrl-F to find it. Seems a little weird that the only thing
connecting the blog and the entire development process wouldn't merit a
button or ribbon or something?
