### ISSUE TITLE
NCBI taxonomy data not found and unable to connect to update server

### ISSUE THREAD

**Issue by bonniethesheng** [gjospin/PhyloSift#497]
Hi all,
I am super new to PhyloSift. I have downloaded the whole package https://figshare.com/articles/PhyloSift_markers_database/5755404, unzipped all four folders. Update the marker folder with the 20140913 one, and update the NCBI file from ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/ by copying all files in taxdmp.zip to the NCBI folder. However, after I typed in
 ./phylosift all --paired tutorial_data/HMP_1.fastq.gz tutorial_data/HMP_2.fastq.gz
I till got the error: 
NCBI taxonomy data not found and unable to connect to update server, please check your phylosift configuration and internet connection!
Does anyone know what I can do?

Thanks a lot for any suggestion!

Sincerely,
Lina

**Comment by gjospin** [comment]
What is the path where your ncbi folder is?
It should look like /home/username/share/phylosfit/ncbi

**Comment by bonniethesheng** [comment]
Thank you very much!!! It worked after I moved the phylosift folder from home to the share folder. I am super new to Linux system as well. Could you please explain that why the folder has to be in the share folder?

Thanks,
Lina

**Comment by gjospin** [comment]
Hi,
I don't think it's a requirement, more like a convention. You could also
modify the phylosiftrc file to change the path that PhyloSift will use to
look for the databases.
From what I understand, when software adds/downloads or need a particular
set of things, the common usage is to add that to a "share" folder so we
just followed that guideline. It can then be referenced or pointed to by
everyone using the same software.
As you install other tools, you might end up with other directories labeled
with the new software name there.

I hope this helps.

**Comment by bonniethesheng** [comment]
Thank you very much!!
