### ISSUE TITLE
Clarify legal issues with redistribution of rRNA data

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#57]
Jonathan to ask campus lawyer and his uncle

**Comment by hollybik** [comment]
It seems like fair use if we use take NCBI accession numbers, as long as we don't use the SILVA alignments (they have their own specific license).

Need to be able to redistribute things without restrictions on redistribution (unrestricted redistribution licenses)

**Comment by hollybik** [comment]
I talked to the SILVA people at the GSC meeting in China, and they are perfectly happy for us to use their taxonomy as long as it is for noncommercial academic use (and the software is redistributed for use in this way). If we are happy taking this route, all we'd need to do is add a disclaimer when users start to run analyses....

SILVA actively has a postdoc working to streamline the taxonomy they pull in from NCBI - so the taxonomy will get better with each new SILVA update and we can pull these improvements into PhyloSift when we update the rRNA databases periodically.

**Comment by koadman** [comment]
Strict noncommercial licensing is not compatible with our existing licensing structure. We may include some "fair use" information from silva such as sequence IDs but no taxonomy info will be used.
