### ISSUE TITLE
Build AMPHORA markers from aligned sequences

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#58]
Whiteboard picture: http://pic.twitter.com/AwzJsoPD

**Comment by gjospin** [comment]
Does taxit do anything special besides placing all the correct files in a directory ?
Having to require Python for it is annoying, but manageable if need be.

**Comment by gjospin** [comment]
Also we can agree on file naming conventions .tree or .tre or .fasttree
Same for fasta or faa.

I know there are lots of file with multiple extensions like .final.tre.  The marker building script may be a good time to eliminate all the ambiguous naming conventions from the start of the project

**Comment by hollybik** [comment]
It looks like taxit organizes and manages the reference packages required by placer - and "Refpkgs are primarily key-value stores for files and metadata." pplacer looks pretty reliant on taxit, so it might be easier just to deal with the python requirement than try to get around using taxit altogether...

see detailed documentation here: http://fhcrc.github.com/taxtastic/commands.html#new-database

I vote for .fasta and .tree since those are the most standard extensions I typically come across

**Comment by gjospin** [comment]
This should be uploaded to the devel_gjospin branch under the following commit code:
34f5352ad201a69b7152c203d062743a4300612e
