### ISSUE TITLE
can't download?

### ISSUE THREAD

**Issue by dbrami** [gjospin/PhyloSift#69]
Hi,

I could not download the binary from "http://edhar.genomecenter.ucdavis.edu/~koadman/amphora2/amphora2_latest.tar.bz2". Is this a known problem?

**Comment by koadman** [comment]
The web server was taken down for maintenance yesterday (February 2, 2012) and is expected to come back online today (Feb. 3rd, 2012). In the meantime you can still access the source code and build the latest pipeline yourself using the script available here:
https://raw.github.com/gjospin/Amphora-2/master/tools/package_standalone.pl

note that script requires development tools including git and others to be installed.
