### ISSUE TITLE
refactor modules into "subcommands"

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#75]
Right now the software has a frontend script that parses arguments. That script needs to know all the arguments that can go to submodules (e.g. the fast screening, marker alignment, read placement). I propose a refactor so that submodules parse their own command lines. This will improve modularity, and give greater flexibility for command syntax.  This approach is similar to what git and many other programs use. Submodules can thus have a consistent interface, possibly deriving from a common parent object.

**Comment by gjospin** [comment]
When this happens, prevent from creating PS_temp directories when creating marker reference packages when using the build_marker mode

**Comment by koadman** [comment]
There should be a parent object interface called PSCommand or PhyloSiftCommand or something like that which defines a function "run" that can take the command-line arguments. All subcommands (search, align, place, etc) should implement that interface, then PhyloSift.pm need only sub out to the appropriate command.

**Comment by koadman** [comment]
This has been implemented using the App:Cmd system
