### ISSUE TITLE
Paired end reads

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#83]
-paired Functionality is broken.

I was using gzipped file, not sure yet the break comes from reading from gzip or fastq format.

**Comment by koadman** [comment]
also think about interleaved paired fastq

**Comment by gjospin** [comment]
Moving the write candidate call to inside get_hits generates 2 problems

Streaming hits requires writing to a pipe that may get filled up if no hits are found for a while.  Possbile solution : Call write candidates function every X reads processed to prevent the stream from filling up ?
Writing a candidate when we get hits don't check for multiple hits / Top hit on different markers (in the case of a longer contig).  Possible solution : keep a record of current sequence processed + stats associated with that read until a new sequence gets processed

**Comment by gjospin** [comment]
Had to rework the Octopus to write reads to a file instead of to a pipe due to the buffer filling up.

Not printing the quality scores AND printing both reads from a pair to bowtie_pipe1 seems to get the stream unstuck.

Now reporting a rapsearch out of frame error : "Error, alignment length not multiple of 3!  FIXME: need to pull frameshift from full blastx" from the write candidate function.

**Comment by gjospin** [comment]
Paired ends reads are being handled correctly, merging the reads into 1 sequence after the alignment step.

Closing and opening a Bowtie paired ends reads when using (assigned to @koadman )
