### ISSUE TITLE
start an online user support forum

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#84]

**Comment by koadman** [comment]
we need an online space where users can go to ask questions about phylosift. this space should: 
- allow subscription for notification of new messages
- be publicly archived and indexed by google and other search engines
- have some kind of spam filter (e.g. signup required)

**Comment by hollybik** [comment]
Started up a Google Group for users:  https://groups.google.com/d/forum/phylosift

Will be working to add more content to this and posting about this on Twitter/Blog tomorrow.

**Comment by koadman** [comment]
Our documentation, web sites etc will need to be updated to point to this of course...

**Comment by hollybik** [comment]
Updated with new blog post, twitter updates, and on all the various "About" pages on Jonathan's and PhyloSift's blog. Also  updated documentation and committed changes to Readme file.
