### ISSUE TITLE
need consistent descriptions of program options

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#87]
program options can be long, e.g. `--help`, or short form e.g. `-h`. Our option parser also supports single - long options, e.g. `-help`, but I suggest we avoid these since GNU convention seems to always be --, and using single dash for long options is overloaded with strings of short options. For example `tar -xvf blahblah.tar.gz` is a synonym for `tar -x -v -f blahblah.tar.gz`, but `phylosift -help` is not a synonym for `phylosift -h -e -l -p`!

**Comment by mayalowe** [comment]
Should I also add missing options to the documentation, such as -f?

**Comment by koadman** [comment]
yes!

**Comment by mayalowe** [comment]
Only one undocumented option (--updated_markers=[0,1]), but all single - long options are gone and 99% of options are documented.  I left --updated_markers alone for now because it will require some reformatting of the README if we include it and want it to look 'nice'.
