### ISSUE TITLE
Writeup a coding convention document for GitHub

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#90]

**Comment by koadman** [comment]
This should really be assigned to both Guillaume and I, but github will only take one assignee.
I've started stubbing out a wiki page, Guillaume, can you fill some of it in?
https://github.com/gjospin/PhyloSift/wiki/PhyloSift-coding-convention

**Comment by gjospin** [comment]
Filled in most of it.

What should go in the Error checking part ?  usage of debug ?

**Comment by koadman** [comment]
I put in some suggestions for the error checking part but the list of error types to handle needs to get built out a bit further.

**Comment by koadman** [comment]
The wiki seems to be pretty well filled out, now we just need to refactor the code to match!  Closing this issue.
